openapi: 3.1.0
components:
  schemas:
    ReserveNow:
      type: object
      description: Request to reserve an EVSE for a Token.
      required:
      - response_url
      - token
      - expiry_date
      - reservation_id
      - location_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        token:
          $ref: ../tokens/schema.yaml#/components/schemas/Token
        expiry_date:
          type: string
          format: date-time
        reservation_id:
          type: string
          maxLength: 36
          description: Unique reservation ID.
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location to reserve at.
        evse_uid:
          type: string
          maxLength: 36
          description: Optional EVSE.uid of the specific EVSE to reserve.
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
      additionalProperties: true
    StartSession:
      type: object
      description: Request to start a charging session.
      required:
      - response_url
      - token
      - location_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        token:
          $ref: ../tokens/schema.yaml#/components/schemas/Token
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location to start charging at.
        evse_uid:
          type: string
          maxLength: 36
          description: Optional EVSE.uid. Required when connector_id is set.
        connector_id:
          type: string
          maxLength: 36
          description: Optional Connector.id. Required when START_SESSION_CONNECTOR_REQUIRED capability is set.
        authorization_reference:
          type: string
          maxLength: 36
          description: Reference to the authorization given by the eMSP.
      additionalProperties: true
    StopSession:
      type: object
      description: Request to stop an ongoing charging session.
      required:
      - response_url
      - session_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        session_id:
          type: string
          maxLength: 36
          description: Session.id of the Session to stop.
      additionalProperties: true
    UnlockConnector:
      type: object
      description: Request to unlock a connector (for help desk operators).
      required:
      - response_url
      - location_id
      - evse_uid
      - connector_id
      properties:
        response_url:
          type: string
          format: uri
          maxLength: 255
          description: URL that the CommandResult POST should be sent to.
        location_id:
          type: string
          maxLength: 36
          description: Location.id of the Location.
        evse_uid:
          type: string
          maxLength: 36
          description: EVSE.uid of the EVSE.
        connector_id:
          type: string
          maxLength: 36
          description: Connector.id of the Connector to unlock.
      additionalProperties: true
    CommandResponse:
      type: object
      description: Immediate response from CPO indicating whether the command was understood and forwarded (not the result from the Charge Point itself).
      required:
      - result
      properties:
        result:
          $ref: '#/components/schemas/CommandResponseType'
        message:
          type: array
          items:
            $ref: ../../components/schema.yaml#/components/schemas/DisplayText
          description: Human-readable description of the result.
      additionalProperties: true
    CommandResponseType:
      description: Result of the command request.
      type: string
      enum:
      - NOT_SUPPORTED
      - REJECTED
      - ACCEPTED
      - TIMEOUT
      - UNKNOWN_SESSION
