openapi: 3.1.0
info:
  title: OCPI 2.1.1 Commands Sender Interface
  description: The Sender Interface is typically implemented by the eMSP and receives asynchronous command results.
  version: 2.1.1
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.1.1 Specification
  url: https://github.com/ocpi/ocpi
security:
- ocpiAuthorization: []
components:
  securitySchemes:
    ocpiAuthorization:
      $ref: ../../components/schema.yaml#/components/securitySchemes/ocpiAuthorization
paths:
  /commands:
    post:
      operationId: senderPostCommandResult
      summary: Receive asynchronous command result
      tags:
      - Commands
      parameters:
      - $ref: ../../components/parameters.yaml#/components/parameters/X-Request-ID
      - $ref: ../../components/parameters.yaml#/components/parameters/X-Correlation-ID
      - $ref: ../../components/parameters.yaml#/components/parameters/OCPI-from-country-code
      - $ref: ../../components/parameters.yaml#/components/parameters/OCPI-from-party-id
      - $ref: ../../components/parameters.yaml#/components/parameters/OCPI-to-country-code
      - $ref: ../../components/parameters.yaml#/components/parameters/OCPI-to-party-id
      requestBody:
        description: Result of the command request.
        required: true
        content:
          application/json:
            schema:
              $ref: ./schema.yaml#/components/schemas/CommandResponse
      responses:
        '200':
          $ref: ../../components/schema.yaml#/components/responses/OCPISuccessResponse
        '400':
          $ref: ../../components/schema.yaml#/components/responses/OCPIErrorResponse
        '401':
          $ref: ../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse
