openapi: 3.1.0
components:
  schemas:
    Credentials:
      type: object
      description: |
        Every role needs a unique combination of: role, party_id and country_code.
      properties:
        token:
          type: string
          maxLength: 64
          description: |
            The credentials token for the other party to authenticate in your system.
            It should only contain printable non-whitespace ASCII characters, that is,
            characters with Unicode code points from the range of U+0021 up to and including U+007E.
        url:
          type: string
          format: uri
          description: The URL to your API versions endpoint.
        roles:
          type: array
          minItems: 1
          description: List of the roles this party provides.
          items:
            $ref: "#/components/schemas/CredentialsRole"
      required:
        - token
        - url
        - roles

    CredentialsRole:
      type: object
      description: Role information for a credentials exchange.
      properties:
        role:
          $ref: "../hubclientinfo/schema.yaml#/components/schemas/Role"
          description: Type of role.
        business_details:
          $ref: "../../components/schema.yaml#/components/schemas/BusinessDetails"
          description: Details of this party.
        party_id:
          type: string
          minLength: 3
          maxLength: 3
          description: CPO, eMSP (or other role) ID of this party (following the ISO-15118 standard).
        country_code:
          type: string
          minLength: 2
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the country this party is operating in.
      required:
        - role
        - business_details
        - party_id
        - country_code
