// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// CdrsSenderClient calls the Cdrs sender interface on a peer.
type CdrsSenderClient struct {
	c    *core.Client
	base string
}

// NewCdrsSenderClient binds a client to baseURL (the peer's cdrs endpoint URL).
func NewCdrsSenderClient(c *core.Client, baseURL string) *CdrsSenderClient {
	return &CdrsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *CdrsSenderClient) GetCdrs(ctx context.Context, p core.PageOpts) (core.Page[CDR], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[CDR]{}, err
	}
	out, err := core.Decode[[]CDR](resp)
	if err != nil {
		return core.Page[CDR]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[CDR]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

// CdrsSenderHandler handles inbound Cdrs sender requests.
type CdrsSenderHandler interface {
	GetCdrs(ctx context.Context, req core.PageReq) (core.Page[CDR], *status.Error)
}

// RegisterCdrsSender registers h's routes on mux under basePath (the module mount path).
func RegisterCdrsSender(mux *core.Mux, basePath string, h CdrsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetCdrs(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
}
