// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"time"
)

// ReserveNow: Request to reserve an EVSE for a Token.
type ReserveNow struct {
	ResponseURL            string    `json:"response_url" validate:"required,max=255"`
	Token                  Token     `json:"token" validate:"required"`
	ExpiryDate             time.Time `json:"expiry_date" validate:"required"`
	ReservationID          string    `json:"reservation_id" validate:"required,max=36"`
	LocationID             string    `json:"location_id" validate:"required,max=36"`
	EVSEUID                *string   `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	AuthorizationReference *string   `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
}

// StartSession: Request to start a charging session.
type StartSession struct {
	ResponseURL            string  `json:"response_url" validate:"required,max=255"`
	Token                  Token   `json:"token" validate:"required"`
	LocationID             string  `json:"location_id" validate:"required,max=36"`
	EVSEUID                *string `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	ConnectorID            *string `json:"connector_id,omitempty" validate:"omitempty,max=36"`
	AuthorizationReference *string `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
}

// StopSession: Request to stop an ongoing charging session.
type StopSession struct {
	ResponseURL string `json:"response_url" validate:"required,max=255"`
	SessionID   string `json:"session_id" validate:"required,max=36"`
}

// UnlockConnector: Request to unlock a connector (for help desk operators).
type UnlockConnector struct {
	ResponseURL string `json:"response_url" validate:"required,max=255"`
	LocationID  string `json:"location_id" validate:"required,max=36"`
	EVSEUID     string `json:"evse_uid" validate:"required,max=36"`
	ConnectorID string `json:"connector_id" validate:"required,max=36"`
}

// CommandResponse: Immediate response from CPO indicating whether the command was understood and forwarded (not the result from the Charge Point itself).
type CommandResponse struct {
	Result  CommandResponseType `json:"result" validate:"required"`
	Message []DisplayText       `json:"message,omitempty"`
}

// CommandResponseType: Result of the command request.
type CommandResponseType string

const (
	CommandResponseTypeNotSupported   CommandResponseType = "NOT_SUPPORTED"
	CommandResponseTypeRejected       CommandResponseType = "REJECTED"
	CommandResponseTypeAccepted       CommandResponseType = "ACCEPTED"
	CommandResponseTypeTimeout        CommandResponseType = "TIMEOUT"
	CommandResponseTypeUnknownSession CommandResponseType = "UNKNOWN_SESSION"
)
