// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"github.com/shopspring/decimal"
)

// DisplayText: Multi-language text with a language code.
type DisplayText struct {
	Language string `json:"language" validate:"required,len=2"`
	Text     string `json:"text" validate:"required,max=512"`
}

// Price: Price with VAT information.
type Price struct {
	ExclVAT decimal.Decimal  `json:"excl_vat" validate:"required"`
	InclVAT *decimal.Decimal `json:"incl_vat,omitempty"`
}

// BusinessDetails: Details of an operator, owner, or suboperator.
type BusinessDetails struct {
	Name    string  `json:"name" validate:"required,max=100"`
	Website *string `json:"website,omitempty" validate:"omitempty,max=255"`
	Logo    *Image  `json:"logo,omitempty"`
}

// Image: Reference to an image with metadata.
type Image struct {
	URL       string        `json:"url" validate:"required,max=255"`
	Thumbnail *string       `json:"thumbnail,omitempty" validate:"omitempty,max=255"`
	Category  ImageCategory `json:"category" validate:"required"`
	Type      string        `json:"type" validate:"required,max=4"`
	Width     *int          `json:"width,omitempty"`
	Height    *int          `json:"height,omitempty"`
}

// ImageCategory: The category of an image to obtain the correct usage.
type ImageCategory string

const (
	ImageCategoryCharger  ImageCategory = "CHARGER"
	ImageCategoryEntrance ImageCategory = "ENTRANCE"
	ImageCategoryLocation ImageCategory = "LOCATION"
	ImageCategoryNetwork  ImageCategory = "NETWORK"
	ImageCategoryOperator ImageCategory = "OPERATOR"
	ImageCategoryOther    ImageCategory = "OTHER"
	ImageCategoryOwner    ImageCategory = "OWNER"
)
