// Code generated by gocpi codegen. DO NOT EDIT.

package v211

// Credentials: Credentials object containing the token, versions URL, and party identity.
type Credentials struct {
	Token           string          `json:"token" validate:"required,max=64"`
	URL             string          `json:"url" validate:"required,max=255"`
	BusinessDetails BusinessDetails `json:"business_details" validate:"required"`
	PartyID         string          `json:"party_id" validate:"required,len=3"`
	CountryCode     string          `json:"country_code" validate:"required,len=2"`
}
