// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"github.com/shopspring/decimal"
	"time"
)

// Location: The Location object describes the location and its properties where a group of EVSEs that belong together are installed.
type Location struct {
	CountryCode        string                  `json:"country_code" validate:"required,len=2"`
	PartyID            string                  `json:"party_id" validate:"required,len=3"`
	ID                 string                  `json:"id" validate:"required,max=36"`
	Publish            bool                    `json:"publish"`
	PublishAllowedTo   []PublishTokenType      `json:"publish_allowed_to,omitempty"`
	Name               *string                 `json:"name,omitempty" validate:"omitempty,max=255"`
	Address            string                  `json:"address" validate:"required,max=45"`
	City               string                  `json:"city" validate:"required,max=45"`
	PostalCode         *string                 `json:"postal_code,omitempty" validate:"omitempty,max=10"`
	State              *string                 `json:"state,omitempty" validate:"omitempty,max=20"`
	Country            string                  `json:"country" validate:"required,max=3"`
	Coordinates        GeoLocation             `json:"coordinates" validate:"required"`
	RelatedLocations   []AdditionalGeoLocation `json:"related_locations,omitempty"`
	ParkingType        *ParkingType            `json:"parking_type,omitempty"`
	Evses              []EVSE                  `json:"evses,omitempty"`
	Directions         []DisplayText           `json:"directions,omitempty"`
	Operator           *BusinessDetails        `json:"operator,omitempty"`
	Suboperator        *BusinessDetails        `json:"suboperator,omitempty"`
	Owner              *BusinessDetails        `json:"owner,omitempty"`
	Facilities         []Facility              `json:"facilities,omitempty"`
	TimeZone           string                  `json:"time_zone" validate:"required,max=255"`
	OpeningTimes       *Hours                  `json:"opening_times,omitempty"`
	ChargingWhenClosed *bool                   `json:"charging_when_closed,omitempty"`
	Images             []Image                 `json:"images,omitempty"`
	EnergyMix          *EnergyMix              `json:"energy_mix,omitempty"`
	LastUpdated        time.Time               `json:"last_updated" validate:"required"`
}

// EVSE: The EVSE object describes the part of a Charging Station that controls one or more Connectors. For each EVSE, a set of Connectors is given.
type EVSE struct {
	UID                 string               `json:"uid" validate:"required,max=36"`
	EVSEID              *string              `json:"evse_id,omitempty" validate:"omitempty,max=48"`
	Status              Status               `json:"status" validate:"required"`
	StatusSchedule      []StatusSchedule     `json:"status_schedule,omitempty"`
	Capabilities        []Capability         `json:"capabilities,omitempty"`
	Connectors          []Connector          `json:"connectors" validate:"required,min=1"`
	FloorLevel          *string              `json:"floor_level,omitempty" validate:"omitempty,max=4"`
	Coordinates         *GeoLocation         `json:"coordinates,omitempty"`
	PhysicalReference   *string              `json:"physical_reference,omitempty" validate:"omitempty,max=16"`
	Directions          []DisplayText        `json:"directions,omitempty"`
	ParkingRestrictions []ParkingRestriction `json:"parking_restrictions,omitempty"`
	Images              []Image              `json:"images,omitempty"`
	LastUpdated         time.Time            `json:"last_updated" validate:"required"`
}

// Connector: A connector is the socket or cable and plug available for the EV to use.
type Connector struct {
	ID                 string          `json:"id" validate:"required,max=36"`
	Standard           ConnectorType   `json:"standard" validate:"required"`
	Format             ConnectorFormat `json:"format" validate:"required"`
	PowerType          PowerType       `json:"power_type" validate:"required"`
	MaxVoltage         int             `json:"max_voltage" validate:"required"`
	MaxAmperage        int             `json:"max_amperage" validate:"required"`
	MaxElectricPower   *int            `json:"max_electric_power,omitempty"`
	TariffIds          []string        `json:"tariff_ids,omitempty"`
	TermsAndConditions *string         `json:"terms_and_conditions,omitempty" validate:"omitempty,max=255"`
	LastUpdated        time.Time       `json:"last_updated" validate:"required"`
}

// LocationPatch: Partial Location object for PATCH. MUST contain last_updated.
type LocationPatch struct {
	Name               *string                 `json:"name,omitempty" validate:"omitempty,max=255"`
	Address            *string                 `json:"address,omitempty" validate:"omitempty,max=45"`
	City               *string                 `json:"city,omitempty" validate:"omitempty,max=45"`
	PostalCode         *string                 `json:"postal_code,omitempty" validate:"omitempty,max=10"`
	State              *string                 `json:"state,omitempty" validate:"omitempty,max=20"`
	Country            *string                 `json:"country,omitempty" validate:"omitempty,max=3"`
	Coordinates        *GeoLocation            `json:"coordinates,omitempty"`
	RelatedLocations   []AdditionalGeoLocation `json:"related_locations,omitempty"`
	ParkingType        *ParkingType            `json:"parking_type,omitempty"`
	Evses              []EVSE                  `json:"evses,omitempty"`
	Directions         []DisplayText           `json:"directions,omitempty"`
	Operator           *BusinessDetails        `json:"operator,omitempty"`
	Suboperator        *BusinessDetails        `json:"suboperator,omitempty"`
	Owner              *BusinessDetails        `json:"owner,omitempty"`
	Facilities         []Facility              `json:"facilities,omitempty"`
	TimeZone           *string                 `json:"time_zone,omitempty" validate:"omitempty,max=255"`
	OpeningTimes       *Hours                  `json:"opening_times,omitempty"`
	ChargingWhenClosed *bool                   `json:"charging_when_closed,omitempty"`
	Images             []Image                 `json:"images,omitempty"`
	EnergyMix          *EnergyMix              `json:"energy_mix,omitempty"`
	Publish            *bool                   `json:"publish,omitempty"`
	PublishAllowedTo   []PublishTokenType      `json:"publish_allowed_to,omitempty"`
	LastUpdated        time.Time               `json:"last_updated" validate:"required"`
}

// EvsePatch: Partial EVSE object for PATCH. MUST contain last_updated.
type EvsePatch struct {
	UID                 *string              `json:"uid,omitempty" validate:"omitempty,max=36"`
	EVSEID              *string              `json:"evse_id,omitempty" validate:"omitempty,max=48"`
	Status              *Status              `json:"status,omitempty"`
	StatusSchedule      []StatusSchedule     `json:"status_schedule,omitempty"`
	Capabilities        []Capability         `json:"capabilities,omitempty"`
	Connectors          []Connector          `json:"connectors,omitempty"`
	FloorLevel          *string              `json:"floor_level,omitempty" validate:"omitempty,max=4"`
	Coordinates         *GeoLocation         `json:"coordinates,omitempty"`
	PhysicalReference   *string              `json:"physical_reference,omitempty" validate:"omitempty,max=16"`
	Directions          []DisplayText        `json:"directions,omitempty"`
	ParkingRestrictions []ParkingRestriction `json:"parking_restrictions,omitempty"`
	Images              []Image              `json:"images,omitempty"`
	LastUpdated         time.Time            `json:"last_updated" validate:"required"`
}

// ConnectorPatch: Partial Connector object for PATCH. MUST contain last_updated.
type ConnectorPatch struct {
	ID                 *string          `json:"id,omitempty" validate:"omitempty,max=36"`
	Standard           *ConnectorType   `json:"standard,omitempty"`
	Format             *ConnectorFormat `json:"format,omitempty"`
	PowerType          *PowerType       `json:"power_type,omitempty"`
	MaxVoltage         *int             `json:"max_voltage,omitempty"`
	MaxAmperage        *int             `json:"max_amperage,omitempty"`
	MaxElectricPower   *int             `json:"max_electric_power,omitempty"`
	TariffIds          []string         `json:"tariff_ids,omitempty"`
	TermsAndConditions *string          `json:"terms_and_conditions,omitempty" validate:"omitempty,max=255"`
	LastUpdated        time.Time        `json:"last_updated" validate:"required"`
}

// PublishTokenType: Defines the set of token properties used to identify tokens allowed to view a Location.
type PublishTokenType struct {
	UID          *string    `json:"uid,omitempty" validate:"omitempty,max=36"`
	Type         *TokenType `json:"type,omitempty"`
	VisualNumber *string    `json:"visual_number,omitempty" validate:"omitempty,max=64"`
	Issuer       *string    `json:"issuer,omitempty" validate:"omitempty,max=64"`
	GroupID      *string    `json:"group_id,omitempty" validate:"omitempty,max=36"`
}

// StatusSchedule: A planned status update for an EVSE.
type StatusSchedule struct {
	PeriodBegin time.Time  `json:"period_begin" validate:"required"`
	PeriodEnd   *time.Time `json:"period_end,omitempty"`
	Status      Status     `json:"status" validate:"required"`
}

// Status: The status of an EVSE.
type Status string

const (
	StatusAvailable   Status = "AVAILABLE"
	StatusBlocked     Status = "BLOCKED"
	StatusCharging    Status = "CHARGING"
	StatusInoperative Status = "INOPERATIVE"
	StatusOutoforder  Status = "OUTOFORDER"
	StatusPlanned     Status = "PLANNED"
	StatusRemoved     Status = "REMOVED"
	StatusReserved    Status = "RESERVED"
	StatusUnknown     Status = "UNKNOWN"
)

// Capability: The capabilities of an EVSE.
type Capability string

const (
	CapabilityChargingProfileCapable        Capability = "CHARGING_PROFILE_CAPABLE"
	CapabilityChargingPreferencesCapable    Capability = "CHARGING_PREFERENCES_CAPABLE"
	CapabilityChipCardSupport               Capability = "CHIP_CARD_SUPPORT"
	CapabilityContactlessCardSupport        Capability = "CONTACTLESS_CARD_SUPPORT"
	CapabilityCreditCardPayable             Capability = "CREDIT_CARD_PAYABLE"
	CapabilityDebitCardPayable              Capability = "DEBIT_CARD_PAYABLE"
	CapabilityPedTerminal                   Capability = "PED_TERMINAL"
	CapabilityRemoteStartStopCapable        Capability = "REMOTE_START_STOP_CAPABLE"
	CapabilityReservable                    Capability = "RESERVABLE"
	CapabilityRfidReader                    Capability = "RFID_READER"
	CapabilityStartSessionConnectorRequired Capability = "START_SESSION_CONNECTOR_REQUIRED"
	CapabilityTokenGroupCapable             Capability = "TOKEN_GROUP_CAPABLE"
	CapabilityUnlockCapable                 Capability = "UNLOCK_CAPABLE"
)

// ConnectorFormat: The format of a connector (socket or attached cable).
type ConnectorFormat string

const (
	ConnectorFormatSocket ConnectorFormat = "SOCKET"
	ConnectorFormatCable  ConnectorFormat = "CABLE"
)

// ConnectorType: The socket or plug standard of the connector.
type ConnectorType string

const (
	ConnectorTypeChademo            ConnectorType = "CHADEMO"
	ConnectorTypeChaoji             ConnectorType = "CHAOJI"
	ConnectorTypeDomesticA          ConnectorType = "DOMESTIC_A"
	ConnectorTypeDomesticB          ConnectorType = "DOMESTIC_B"
	ConnectorTypeDomesticC          ConnectorType = "DOMESTIC_C"
	ConnectorTypeDomesticD          ConnectorType = "DOMESTIC_D"
	ConnectorTypeDomesticE          ConnectorType = "DOMESTIC_E"
	ConnectorTypeDomesticF          ConnectorType = "DOMESTIC_F"
	ConnectorTypeDomesticG          ConnectorType = "DOMESTIC_G"
	ConnectorTypeDomesticH          ConnectorType = "DOMESTIC_H"
	ConnectorTypeDomesticI          ConnectorType = "DOMESTIC_I"
	ConnectorTypeDomesticJ          ConnectorType = "DOMESTIC_J"
	ConnectorTypeDomesticK          ConnectorType = "DOMESTIC_K"
	ConnectorTypeDomesticL          ConnectorType = "DOMESTIC_L"
	ConnectorTypeDomesticM          ConnectorType = "DOMESTIC_M"
	ConnectorTypeDomesticN          ConnectorType = "DOMESTIC_N"
	ConnectorTypeDomesticO          ConnectorType = "DOMESTIC_O"
	ConnectorTypeGbtAc              ConnectorType = "GBT_AC"
	ConnectorTypeGbtDc              ConnectorType = "GBT_DC"
	ConnectorTypeIec603092Single16  ConnectorType = "IEC_60309_2_single_16"
	ConnectorTypeIec603092Three16   ConnectorType = "IEC_60309_2_three_16"
	ConnectorTypeIec603092Three32   ConnectorType = "IEC_60309_2_three_32"
	ConnectorTypeIec603092Three64   ConnectorType = "IEC_60309_2_three_64"
	ConnectorTypeIec62196T1         ConnectorType = "IEC_62196_T1"
	ConnectorTypeIec62196T1Combo    ConnectorType = "IEC_62196_T1_COMBO"
	ConnectorTypeIec62196T2         ConnectorType = "IEC_62196_T2"
	ConnectorTypeIec62196T2Combo    ConnectorType = "IEC_62196_T2_COMBO"
	ConnectorTypeIec62196T3a        ConnectorType = "IEC_62196_T3A"
	ConnectorTypeIec62196T3c        ConnectorType = "IEC_62196_T3C"
	ConnectorTypeNema520            ConnectorType = "NEMA_5_20"
	ConnectorTypeNema630            ConnectorType = "NEMA_6_30"
	ConnectorTypeNema650            ConnectorType = "NEMA_6_50"
	ConnectorTypeNema1030           ConnectorType = "NEMA_10_30"
	ConnectorTypeNema1050           ConnectorType = "NEMA_10_50"
	ConnectorTypeNema1430           ConnectorType = "NEMA_14_30"
	ConnectorTypeNema1450           ConnectorType = "NEMA_14_50"
	ConnectorTypePantographBottomUp ConnectorType = "PANTOGRAPH_BOTTOM_UP"
	ConnectorTypePantographTopDown  ConnectorType = "PANTOGRAPH_TOP_DOWN"
	ConnectorTypeTeslaR             ConnectorType = "TESLA_R"
	ConnectorTypeTeslaS             ConnectorType = "TESLA_S"
)

// PowerType: AC or DC power type.
type PowerType string

const (
	PowerTypeAc1Phase      PowerType = "AC_1_PHASE"
	PowerTypeAc2Phase      PowerType = "AC_2_PHASE"
	PowerTypeAc2PhaseSplit PowerType = "AC_2_PHASE_SPLIT"
	PowerTypeAc3Phase      PowerType = "AC_3_PHASE"
	PowerTypeDc            PowerType = "DC"
)

// ParkingType: The general type of parking at this location.
type ParkingType string

const (
	ParkingTypeAlongMotorway     ParkingType = "ALONG_MOTORWAY"
	ParkingTypeParkingGarage     ParkingType = "PARKING_GARAGE"
	ParkingTypeParkingLot        ParkingType = "PARKING_LOT"
	ParkingTypeOnDriveway        ParkingType = "ON_DRIVEWAY"
	ParkingTypeOnStreet          ParkingType = "ON_STREET"
	ParkingTypeUndergroundGarage ParkingType = "UNDERGROUND_GARAGE"
)

// ParkingRestriction: Restrictions for using a parking spot.
type ParkingRestriction string

const (
	ParkingRestrictionCustomers   ParkingRestriction = "CUSTOMERS"
	ParkingRestrictionDisabled    ParkingRestriction = "DISABLED"
	ParkingRestrictionEvOnly      ParkingRestriction = "EV_ONLY"
	ParkingRestrictionMotorcycles ParkingRestriction = "MOTORCYCLES"
	ParkingRestrictionPlugged     ParkingRestriction = "PLUGGED"
)

// Facility: Facilities at or near the charging location.
type Facility string

const (
	FacilityHotel          Facility = "HOTEL"
	FacilityRestaurant     Facility = "RESTAURANT"
	FacilityCafe           Facility = "CAFE"
	FacilityMall           Facility = "MALL"
	FacilitySupermarket    Facility = "SUPERMARKET"
	FacilitySport          Facility = "SPORT"
	FacilityRecreationArea Facility = "RECREATION_AREA"
	FacilityNature         Facility = "NATURE"
	FacilityMuseum         Facility = "MUSEUM"
	FacilityBikeSharing    Facility = "BIKE_SHARING"
	FacilityBusStop        Facility = "BUS_STOP"
	FacilityTaxiStand      Facility = "TAXI_STAND"
	FacilityTramStop       Facility = "TRAM_STOP"
	FacilityMetroStation   Facility = "METRO_STATION"
	FacilityTrainStation   Facility = "TRAIN_STATION"
	FacilityAirport        Facility = "AIRPORT"
	FacilityParkingLot     Facility = "PARKING_LOT"
	FacilityCarpoolParking Facility = "CARPOOL_PARKING"
	FacilityFuelStation    Facility = "FUEL_STATION"
	FacilityWifi           Facility = "WIFI"
)

// GeoLocation: Geographic coordinates (WGS 84).
type GeoLocation struct {
	Latitude  string `json:"latitude" validate:"required,max=10"`
	Longitude string `json:"longitude" validate:"required,max=11"`
}

// AdditionalGeoLocation: An additional geographic location with an optional human-readable name.
type AdditionalGeoLocation struct {
	Latitude  string       `json:"latitude" validate:"required,max=10"`
	Longitude string       `json:"longitude" validate:"required,max=11"`
	Name      *DisplayText `json:"name,omitempty"`
}

// Hours: Opening and access hours.
type Hours struct {
	Twentyfourseven     bool                `json:"twentyfourseven"`
	RegularHours        []RegularHours      `json:"regular_hours,omitempty"`
	ExceptionalOpenings []ExceptionalPeriod `json:"exceptional_openings,omitempty"`
	ExceptionalClosings []ExceptionalPeriod `json:"exceptional_closings,omitempty"`
}

// RegularHours: Regular recurring operation or access hours.
type RegularHours struct {
	Weekday     int    `json:"weekday" validate:"required"`
	PeriodBegin string `json:"period_begin" validate:"required,max=5"`
	PeriodEnd   string `json:"period_end" validate:"required,max=5"`
}

// ExceptionalPeriod: Specifies one exceptional period for operating hours.
type ExceptionalPeriod struct {
	PeriodBegin time.Time `json:"period_begin" validate:"required"`
	PeriodEnd   time.Time `json:"period_end" validate:"required"`
}

// EnergyMix: Details about the energy supplied at this location.
type EnergyMix struct {
	IsGreenEnergy     bool                  `json:"is_green_energy"`
	EnergySources     []EnergySource        `json:"energy_sources,omitempty"`
	EnvironImpact     []EnvironmentalImpact `json:"environ_impact,omitempty"`
	SupplierName      *string               `json:"supplier_name,omitempty" validate:"omitempty,max=64"`
	EnergyProductName *string               `json:"energy_product_name,omitempty" validate:"omitempty,max=64"`
}

// EnergySource: Breakdown of energy from a specific source.
type EnergySource struct {
	Source     EnergySourceCategory `json:"source" validate:"required"`
	Percentage decimal.Decimal      `json:"percentage" validate:"required"`
}

// EnvironmentalImpact: Amount of environmental waste produced.
type EnvironmentalImpact struct {
	Category EnvironmentalImpactCategory `json:"category" validate:"required"`
	Amount   decimal.Decimal             `json:"amount" validate:"required"`
}

// EnergySourceCategory: Categories of energy sources.
type EnergySourceCategory string

const (
	EnergySourceCategoryNuclear       EnergySourceCategory = "NUCLEAR"
	EnergySourceCategoryGeneralFossil EnergySourceCategory = "GENERAL_FOSSIL"
	EnergySourceCategoryCoal          EnergySourceCategory = "COAL"
	EnergySourceCategoryGas           EnergySourceCategory = "GAS"
	EnergySourceCategoryGeneralGreen  EnergySourceCategory = "GENERAL_GREEN"
	EnergySourceCategorySolar         EnergySourceCategory = "SOLAR"
	EnergySourceCategoryWind          EnergySourceCategory = "WIND"
	EnergySourceCategoryWater         EnergySourceCategory = "WATER"
)

// EnvironmentalImpactCategory: Categories of environmental impact values.
type EnvironmentalImpactCategory string

const (
	EnvironmentalImpactCategoryNuclearWaste  EnvironmentalImpactCategory = "NUCLEAR_WASTE"
	EnvironmentalImpactCategoryCarbonDioxide EnvironmentalImpactCategory = "CARBON_DIOXIDE"
)
