// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"github.com/shopspring/decimal"
	"time"
)

// Session: Describes one charging session. Does not require energy transfer.
type Session struct {
	CountryCode            string           `json:"country_code" validate:"required,len=2"`
	PartyID                string           `json:"party_id" validate:"required,len=3"`
	ID                     string           `json:"id" validate:"required,max=36"`
	StartDateTime          time.Time        `json:"start_date_time" validate:"required"`
	EndDateTime            *time.Time       `json:"end_date_time,omitempty"`
	Kwh                    decimal.Decimal  `json:"kwh" validate:"required"`
	CDRToken               CdrToken         `json:"cdr_token" validate:"required"`
	AuthMethod             AuthMethod       `json:"auth_method" validate:"required"`
	AuthorizationReference *string          `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	LocationID             string           `json:"location_id" validate:"required,max=36"`
	EVSEUID                string           `json:"evse_uid" validate:"required,max=36"`
	ConnectorID            string           `json:"connector_id" validate:"required,max=36"`
	MeterID                *string          `json:"meter_id,omitempty" validate:"omitempty,max=255"`
	Currency               string           `json:"currency" validate:"required,max=3"`
	ChargingPeriods        []ChargingPeriod `json:"charging_periods,omitempty"`
	TotalCost              *Price           `json:"total_cost,omitempty"`
	Status                 SessionStatus    `json:"status" validate:"required"`
	LastUpdated            time.Time        `json:"last_updated" validate:"required"`
}

// SessionPatch: Partial Session object for PATCH. MUST contain last_updated.
type SessionPatch struct {
	EndDateTime            *time.Time       `json:"end_date_time,omitempty"`
	Kwh                    *decimal.Decimal `json:"kwh,omitempty"`
	CDRToken               *CdrToken        `json:"cdr_token,omitempty"`
	AuthMethod             *AuthMethod      `json:"auth_method,omitempty"`
	AuthorizationReference *string          `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	MeterID                *string          `json:"meter_id,omitempty" validate:"omitempty,max=255"`
	Currency               *string          `json:"currency,omitempty" validate:"omitempty,max=3"`
	ChargingPeriods        []ChargingPeriod `json:"charging_periods,omitempty"`
	TotalCost              *Price           `json:"total_cost,omitempty"`
	Status                 *SessionStatus   `json:"status,omitempty"`
	LastUpdated            time.Time        `json:"last_updated" validate:"required"`
}

// SessionStatus: The status of a charging session.
type SessionStatus string

const (
	SessionStatusActive      SessionStatus = "ACTIVE"
	SessionStatusCompleted   SessionStatus = "COMPLETED"
	SessionStatusInvalid     SessionStatus = "INVALID"
	SessionStatusPending     SessionStatus = "PENDING"
	SessionStatusReservation SessionStatus = "RESERVATION"
)
