// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"github.com/shopspring/decimal"
	"time"
)

// Tariff: A Tariff object describes the pricing structure for a charging session.
type Tariff struct {
	CountryCode   string          `json:"country_code" validate:"required,len=2"`
	PartyID       string          `json:"party_id" validate:"required,len=3"`
	ID            string          `json:"id" validate:"required,max=36"`
	Currency      string          `json:"currency" validate:"required,max=3"`
	Type          *TariffType     `json:"type,omitempty"`
	TariffAltText []DisplayText   `json:"tariff_alt_text,omitempty"`
	TariffAltURL  *string         `json:"tariff_alt_url,omitempty" validate:"omitempty,max=255"`
	MinPrice      *Price          `json:"min_price,omitempty"`
	MaxPrice      *Price          `json:"max_price,omitempty"`
	Elements      []TariffElement `json:"elements" validate:"required,min=1"`
	StartDateTime *time.Time      `json:"start_date_time,omitempty"`
	EndDateTime   *time.Time      `json:"end_date_time,omitempty"`
	EnergyMix     *EnergyMix      `json:"energy_mix,omitempty"`
	LastUpdated   time.Time       `json:"last_updated" validate:"required"`
}

// TariffElement: A Tariff Element consists of Price Components and optional Restrictions.
type TariffElement struct {
	PriceComponents []PriceComponent    `json:"price_components" validate:"required,min=1"`
	Restrictions    *TariffRestrictions `json:"restrictions,omitempty"`
}

// PriceComponent: Describes how a specific dimension (energy, time, flat, parking) is priced.
type PriceComponent struct {
	Type     TariffDimensionType `json:"type" validate:"required"`
	Price    decimal.Decimal     `json:"price" validate:"required"`
	VAT      *decimal.Decimal    `json:"vat,omitempty"`
	StepSize int                 `json:"step_size" validate:"required"`
}

// TariffRestrictions: Restrictions that describe when a Tariff Element applies.
type TariffRestrictions struct {
	StartTime   *string                     `json:"start_time,omitempty" validate:"omitempty,max=5"`
	EndTime     *string                     `json:"end_time,omitempty" validate:"omitempty,max=5"`
	StartDate   *string                     `json:"start_date,omitempty" validate:"omitempty,max=10"`
	EndDate     *string                     `json:"end_date,omitempty" validate:"omitempty,max=10"`
	MinKwh      *decimal.Decimal            `json:"min_kwh,omitempty"`
	MaxKwh      *decimal.Decimal            `json:"max_kwh,omitempty"`
	MinCurrent  *decimal.Decimal            `json:"min_current,omitempty"`
	MaxCurrent  *decimal.Decimal            `json:"max_current,omitempty"`
	MinPower    *decimal.Decimal            `json:"min_power,omitempty"`
	MaxPower    *decimal.Decimal            `json:"max_power,omitempty"`
	MinDuration *int                        `json:"min_duration,omitempty"`
	MaxDuration *int                        `json:"max_duration,omitempty"`
	DayOfWeek   []DayOfWeek                 `json:"day_of_week,omitempty"`
	Reservation *ReservationRestrictionType `json:"reservation,omitempty"`
}

// TariffType: Type of tariff.
type TariffType string

const (
	TariffTypeAdHocPayment TariffType = "AD_HOC_PAYMENT"
	TariffTypeProfileCheap TariffType = "PROFILE_CHEAP"
	TariffTypeProfileFast  TariffType = "PROFILE_FAST"
	TariffTypeProfileGreen TariffType = "PROFILE_GREEN"
	TariffTypeRegular      TariffType = "REGULAR"
)

// TariffDimensionType: The dimension being priced: ENERGY (kWh), FLAT (no unit), PARKING_TIME (hours not charging), TIME (hours charging).
type TariffDimensionType string

const (
	TariffDimensionTypeEnergy      TariffDimensionType = "ENERGY"
	TariffDimensionTypeFlat        TariffDimensionType = "FLAT"
	TariffDimensionTypeParkingTime TariffDimensionType = "PARKING_TIME"
	TariffDimensionTypeTime        TariffDimensionType = "TIME"
)

// DayOfWeek: Day of the week.
type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "MONDAY"
	DayOfWeekTuesday   DayOfWeek = "TUESDAY"
	DayOfWeekWednesday DayOfWeek = "WEDNESDAY"
	DayOfWeekThursday  DayOfWeek = "THURSDAY"
	DayOfWeekFriday    DayOfWeek = "FRIDAY"
	DayOfWeekSaturday  DayOfWeek = "SATURDAY"
	DayOfWeekSunday    DayOfWeek = "SUNDAY"
)

// ReservationRestrictionType: Type of reservation restriction in a TariffElement.
type ReservationRestrictionType string

const (
	ReservationRestrictionTypeReservation        ReservationRestrictionType = "RESERVATION"
	ReservationRestrictionTypeReservationExpires ReservationRestrictionType = "RESERVATION_EXPIRES"
)
