// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"time"
)

// Token: Representation of a charging token.
type Token struct {
	CountryCode        string          `json:"country_code" validate:"required,len=2"`
	PartyID            string          `json:"party_id" validate:"required,len=3"`
	UID                string          `json:"uid" validate:"required,max=36"`
	Type               TokenType       `json:"type" validate:"required"`
	ContractID         string          `json:"contract_id" validate:"required,max=36"`
	VisualNumber       *string         `json:"visual_number,omitempty" validate:"omitempty,max=64"`
	Issuer             string          `json:"issuer" validate:"required,max=64"`
	GroupID            *string         `json:"group_id,omitempty" validate:"omitempty,max=36"`
	Valid              bool            `json:"valid"`
	Whitelist          WhitelistType   `json:"whitelist" validate:"required"`
	Language           *string         `json:"language,omitempty" validate:"omitempty,max=2"`
	DefaultProfileType *ProfileType    `json:"default_profile_type,omitempty"`
	EnergyContract     *EnergyContract `json:"energy_contract,omitempty"`
	LastUpdated        time.Time       `json:"last_updated" validate:"required"`
}

// AuthorizationInfo: Information about the authorization status of a Token.
type AuthorizationInfo struct {
	Allowed                AllowedType         `json:"allowed" validate:"required"`
	Token                  Token               `json:"token" validate:"required"`
	Location               *LocationReferences `json:"location,omitempty"`
	AuthorizationReference *string             `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	Info                   *DisplayText        `json:"info,omitempty"`
}

// TokenPatch: Partial Token object for PATCH. MUST contain last_updated.
type TokenPatch struct {
	Type               *TokenType      `json:"type,omitempty"`
	ContractID         *string         `json:"contract_id,omitempty" validate:"omitempty,max=36"`
	VisualNumber       *string         `json:"visual_number,omitempty" validate:"omitempty,max=64"`
	Issuer             *string         `json:"issuer,omitempty" validate:"omitempty,max=64"`
	GroupID            *string         `json:"group_id,omitempty" validate:"omitempty,max=36"`
	Valid              *bool           `json:"valid,omitempty"`
	Whitelist          *WhitelistType  `json:"whitelist,omitempty"`
	Language           *string         `json:"language,omitempty" validate:"omitempty,len=2"`
	DefaultProfileType *string         `json:"default_profile_type,omitempty" validate:"omitempty,max=32"`
	EnergyContract     *EnergyContract `json:"energy_contract,omitempty"`
	LastUpdated        time.Time       `json:"last_updated" validate:"required"`
}

// ProfileType: Type of charging profile selected by the EV driver.
type ProfileType string

const (
	ProfileTypeCheap   ProfileType = "CHEAP"
	ProfileTypeFast    ProfileType = "FAST"
	ProfileTypeGreen   ProfileType = "GREEN"
	ProfileTypeRegular ProfileType = "REGULAR"
)

// LocationReferences: References to a Location and specific EVSEs.
type LocationReferences struct {
	LocationID string   `json:"location_id" validate:"required,max=36"`
	EVSEUids   []string `json:"evse_uids,omitempty"`
}

// EnergyContract: Information about an EV driver's energy supply contract.
type EnergyContract struct {
	SupplierName string  `json:"supplier_name" validate:"required,max=64"`
	ContractID   *string `json:"contract_id,omitempty" validate:"omitempty,max=64"`
}

// TokenType: Type of charging token.
type TokenType string

const (
	TokenTypeAdHocUser TokenType = "AD_HOC_USER"
	TokenTypeAppUser   TokenType = "APP_USER"
	TokenTypeOther     TokenType = "OTHER"
	TokenTypeRfid      TokenType = "RFID"
)

// WhitelistType: Defines the whitelist behavior for a Token.
type WhitelistType string

const (
	WhitelistTypeAlways         WhitelistType = "ALWAYS"
	WhitelistTypeAllowed        WhitelistType = "ALLOWED"
	WhitelistTypeAllowedOffline WhitelistType = "ALLOWED_OFFLINE"
	WhitelistTypeNever          WhitelistType = "NEVER"
)

// AllowedType: Authorization status of a Token.
type AllowedType string

const (
	AllowedTypeAllowed    AllowedType = "ALLOWED"
	AllowedTypeBlocked    AllowedType = "BLOCKED"
	AllowedTypeExpired    AllowedType = "EXPIRED"
	AllowedTypeNoCredit   AllowedType = "NO_CREDIT"
	AllowedTypeNotAllowed AllowedType = "NOT_ALLOWED"
)
