// Code generated by gocpi codegen. DO NOT EDIT.

package v211

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// TokensReceiverClient calls the Tokens receiver interface on a peer.
type TokensReceiverClient struct {
	c    *core.Client
	base string
}

// NewTokensReceiverClient binds a client to baseURL (the peer's tokens endpoint URL).
func NewTokensReceiverClient(c *core.Client, baseURL string) *TokensReceiverClient {
	return &TokensReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *TokensReceiverClient) GetToken(ctx context.Context, countryCode string, partyID string, tokenUID string) (Token, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tokenUID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Token
		return zero, err
	}
	out, err := core.Decode[Token](resp)
	return out.Data, err
}

func (x *TokensReceiverClient) PutToken(ctx context.Context, countryCode string, partyID string, tokenUID string, body Token) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tokenUID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *TokensReceiverClient) PatchToken(ctx context.Context, countryCode string, partyID string, tokenUID string, body TokenPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tokenUID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// TokensReceiverHandler handles inbound Tokens receiver requests.
type TokensReceiverHandler interface {
	GetToken(ctx context.Context, countryCode string, partyID string, tokenUID string) (Token, *status.Error)
	PutToken(ctx context.Context, countryCode string, partyID string, tokenUID string, body Token) *status.Error
	PatchToken(ctx context.Context, countryCode string, partyID string, tokenUID string, body TokenPatch) *status.Error
}

// RegisterTokensReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterTokensReceiver(mux *core.Mux, basePath string, h TokensReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{token_uid}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetToken(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("token_uid"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{token_uid}", func(w http.ResponseWriter, r *http.Request) {
		var body Token
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutToken(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("token_uid"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{token_uid}", func(w http.ResponseWriter, r *http.Request) {
		var body TokenPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchToken(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("token_uid"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
