// Code generated by gocpi codegen. DO NOT EDIT.

package v211

// Version: OCPI version information.
type Version struct {
	Version VersionNumber `json:"version" validate:"required"`
	URL     string        `json:"url" validate:"required,max=255"`
}

// VersionDetails: Detailed information about a specific OCPI version.
type VersionDetails struct {
	Version   VersionNumber `json:"version" validate:"required"`
	Endpoints []Endpoint    `json:"endpoints" validate:"required,min=1"`
}

// Endpoint: Information about a supported OCPI endpoint.
type Endpoint struct {
	Identifier ModuleID      `json:"identifier" validate:"required"`
	Role       InterfaceRole `json:"role" validate:"required"`
	URL        string        `json:"url" validate:"required,max=255"`
}

// InterfaceRole: The role of an interface. SENDER is implemented by the owner of data (for Pull). RECEIVER is implemented by the receiver of data (for Push).
type InterfaceRole string

const (
	InterfaceRoleSender   InterfaceRole = "SENDER"
	InterfaceRoleReceiver InterfaceRole = "RECEIVER"
)

// ModuleID: The identifier of an OCPI module.
type ModuleID string

const (
	ModuleIDCdrs        ModuleID = "cdrs"
	ModuleIDCommands    ModuleID = "commands"
	ModuleIDCredentials ModuleID = "credentials"
	ModuleIDLocations   ModuleID = "locations"
	ModuleIDSessions    ModuleID = "sessions"
	ModuleIDTariffs     ModuleID = "tariffs"
	ModuleIDTokens      ModuleID = "tokens"
)

// VersionNumber: List of known OCPI version numbers.
type VersionNumber string

const (
	VersionNumber20  VersionNumber = "2.0"
	VersionNumber21  VersionNumber = "2.1"
	VersionNumber211 VersionNumber = "2.1.1"
)
