package main

import (
	"bytes"
	"fmt"
	"path/filepath"
	"strings"
)

// role generation order (config.json's roles map has no inherent order, so we
// fix it for reproducible output).
var roleOrder = []string{"cpo", "msp", "hub"}

var roleGoName = map[string]string{"cpo": "CPO", "msp": "MSP", "hub": "Hub"}

type roleEntry struct{ Module, Iface string }

// generateRoles emits role presets (e.g. RegisterCPO) from config.json's
// role -> [module/interface] mapping. Only functional-module interfaces are
// included; the configuration modules (credentials, versions) are handled by the
// handshake package.
func generateRoles(pkg string, cfg *config) {
	var b bytes.Buffer
	b.WriteString("// Code generated by gocpi codegen. DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	b.WriteString("import \"github.com/shiv3/gocpi/core\"\n\n")

	for _, role := range roleOrder {
		var entries []roleEntry
		for _, e := range cfg.Roles[role] {
			parts := strings.SplitN(e, "/", 2)
			if len(parts) != 2 {
				continue
			}
			var iface string
			switch parts[1] {
			case "sender-interface":
				iface = "sender"
			case "receiver-interface":
				iface = "receiver"
			default:
				continue // configuration module ("interface") -> handshake package
			}
			entries = append(entries, roleEntry{Module: parts[0], Iface: iface})
		}
		if len(entries) > 0 {
			emitRole(&b, role, entries)
		}
	}

	writeGoFile(filepath.Join(pkg, "roles.go"), b.Bytes())
	fmt.Printf("generated %s/roles.go\n", pkg)
}

func emitRole(b *bytes.Buffer, role string, entries []roleEntry) {
	rn := roleGoName[role]

	fmt.Fprintf(b, "// %sHandlers groups the functional-module handlers a %s platform provides.\n", rn, rn)
	b.WriteString("// A nil field skips registering that module.\n")
	fmt.Fprintf(b, "type %sHandlers struct {\n", rn)
	for _, e := range entries {
		fmt.Fprintf(b, "\t%s %s%sHandler\n", pascalWord(e.Module), pascalWord(e.Module), pascalWord(e.Iface))
	}
	b.WriteString("}\n\n")

	fmt.Fprintf(b, "// Register%s mounts the %s functional-module endpoints under baseURL;\n", rn, rn)
	b.WriteString("// each module is mounted at baseURL + \"/<module>\".\n")
	fmt.Fprintf(b, "func Register%s(mux *core.Mux, baseURL string, h %sHandlers) {\n", rn, rn)
	for _, e := range entries {
		field := pascalWord(e.Module)
		fmt.Fprintf(b, "\tif h.%s != nil {\n\t\tRegister%s%s(mux, baseURL+%q, h.%s)\n\t}\n",
			field, pascalWord(e.Module), pascalWord(e.Iface), "/"+e.Module, field)
	}
	b.WriteString("}\n\n")
}
