package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// genSchemaDoc emits a JSON-Schema document (schema.json) whose $defs hold every
// generated OCPI type, plus a small schema.go that embeds it and exposes a
// runtime validator.
func genSchemaDoc(schemasDir, pkg string, cfg *config) {
	defs := map[string]any{}
	for _, m := range cfg.typeModules() {
		doc, err := parseSchemaFile(filepath.Join(schemasDir, m.Schema))
		if err != nil {
			fatal(err)
		}
		for _, ns := range doc.Schemas {
			if skipSchemas[ns.Name] {
				continue
			}
			defs[ns.Name] = schemaToJSON(ns.Sch)
		}
	}
	root := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs":   defs,
	}
	data, err := json.MarshalIndent(root, "", "  ")
	if err != nil {
		fatal(err)
	}
	writeRawFile(filepath.Join(pkg, "schema.json"), append(data, '\n'))
	fmt.Printf("generated %s\n", filepath.Join(pkg, "schema.json"))

	writeGoFile(filepath.Join(pkg, "schema.go"), []byte(schemaGoSrc(pkg)))
	fmt.Printf("generated %s\n", filepath.Join(pkg, "schema.go"))
}

// schemaToJSON converts a parsed OpenAPI schema to a JSON-Schema (2020-12) value,
// rewriting cross-file $refs to local "#/$defs/<Name>" references.
func schemaToJSON(s *jsonSchema) map[string]any {
	m := map[string]any{}
	if s.Ref != "" {
		m["$ref"] = "#/$defs/" + refName(s.Ref)
		return m
	}
	if s.Type != "" {
		m["type"] = s.Type
	}
	if len(s.Enum) > 0 {
		m["enum"] = s.Enum
	}
	if s.Items != nil {
		m["items"] = schemaToJSON(s.Items)
	}
	if len(s.Properties) > 0 {
		props := map[string]any{}
		for _, p := range s.Properties {
			props[p.Name] = schemaToJSON(p.Sch)
		}
		m["properties"] = props
	}
	if len(s.Required) > 0 {
		m["required"] = s.Required
	}
	if s.MaxLength != nil {
		m["maxLength"] = *s.MaxLength
	}
	if s.MinLength != nil {
		m["minLength"] = *s.MinLength
	}
	if s.MinItems != nil {
		m["minItems"] = *s.MinItems
	}
	if s.Format != "" && s.Format != "enum" {
		m["format"] = s.Format
	}
	return m
}

func writeRawFile(path string, data []byte) {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(path, data, 0o644); err != nil {
		fatal(err)
	}
}

func schemaGoSrc(pkg string) string {
	return fmt.Sprintf(`// Code generated by gocpi codegen. DO NOT EDIT.

package %s

import (
	_ "embed"
	"sync"

	"github.com/shiv3/gocpi/core/schema"
)

//go:embed schema.json
var schemaJSON []byte

var (
	validatorOnce sync.Once
	validatorInst *schema.Validator
	validatorErr  error
)

// Validator returns the JSON-Schema validator for these OCPI types, built from
// the embedded schema document. It is compiled once and cached.
func Validator() (*schema.Validator, error) {
	validatorOnce.Do(func() {
		validatorInst, validatorErr = schema.New(schemaJSON)
	})
	return validatorInst, validatorErr
}

// ValidateJSON validates raw JSON against the named OCPI type's schema.
func ValidateJSON(typeName string, data []byte) error {
	v, err := Validator()
	if err != nil {
		return err
	}
	return v.Validate(typeName, data)
}
`, pkg)
}
