openapi: 3.1.0
components:
  schemas:
    Credentials:
      type: object
      description: Credentials object containing the token, versions URL, and party identity.
      required:
      - token
      - url
      - business_details
      - party_id
      - country_code
      properties:
        token:
          type: string
          maxLength: 64
          description: The token for the other party to authenticate in your system.
        url:
          type: string
          format: uri
          maxLength: 255
          description: The URL to your API versions endpoint.
        business_details:
          $ref: ../../components/schema.yaml#/components/schemas/BusinessDetails
        party_id:
          type: string
          maxLength: 3
          description: CPO or eMSP ID of this party (following ISO-15118).
          minLength: 3
        country_code:
          type: string
          maxLength: 2
          description: ISO-3166 alpha-2 country code of the country this party is operating in.
          minLength: 2
      additionalProperties: true
