// Code generated by gocpi codegen. DO NOT EDIT.

package versions

// Version: A supported OCPI version and its URL.
type Version struct {
	Version VersionNumber `json:"version" validate:"required"`
	URL     string        `json:"url" validate:"required"`
}

// VersionDetails: Details of a specific OCPI version including its supported endpoints.
type VersionDetails struct {
	Version   VersionNumber `json:"version" validate:"required"`
	Endpoints []Endpoint    `json:"endpoints" validate:"required,min=1"`
}

// Endpoint: An endpoint supported by a platform for a specific OCPI version.
type Endpoint struct {
	Identifier ModuleID      `json:"identifier" validate:"required"`
	Role       InterfaceRole `json:"role" validate:"required"`
	URL        string        `json:"url" validate:"required"`
}

// VersionNumber: List of known versions.
type VersionNumber string

const (
	VersionNumber20  VersionNumber = "2.0"
	VersionNumber21  VersionNumber = "2.1"
	VersionNumber211 VersionNumber = "2.1.1"
	VersionNumber22  VersionNumber = "2.2"
	VersionNumber221 VersionNumber = "2.2.1"
)

// InterfaceRole: The interface role of an endpoint.
type InterfaceRole string

const (
	InterfaceRoleSender   InterfaceRole = "SENDER"
	InterfaceRoleReceiver InterfaceRole = "RECEIVER"
)

// ModuleID: The Module identifiers for each endpoint. Most modules (except Credentials & Registration)
// are optional, but there might be dependencies between modules.
type ModuleID string

const (
	ModuleIDCdrs             ModuleID = "cdrs"
	ModuleIDChargingprofiles ModuleID = "chargingprofiles"
	ModuleIDCommands         ModuleID = "commands"
	ModuleIDCredentials      ModuleID = "credentials"
	ModuleIDHubclientinfo    ModuleID = "hubclientinfo"
	ModuleIDLocations        ModuleID = "locations"
	ModuleIDSessions         ModuleID = "sessions"
	ModuleIDTariffs          ModuleID = "tariffs"
	ModuleIDTokens           ModuleID = "tokens"
)
