// Code generated by gocpi codegen. DO NOT EDIT.

package credentials

import (
	"github.com/shiv3/gocpi/v221/hubclientinfo"
	"github.com/shiv3/gocpi/v221/types"
)

// Credentials: Every role needs a unique combination of: role, party_id and country_code.
type Credentials struct {
	Token string            `json:"token" validate:"required,max=64"`
	URL   string            `json:"url" validate:"required"`
	Roles []CredentialsRole `json:"roles" validate:"required,min=1"`
}

// CredentialsRole: Role information for a credentials exchange.
type CredentialsRole struct {
	Role            hubclientinfo.Role    `json:"role" validate:"required"`
	BusinessDetails types.BusinessDetails `json:"business_details" validate:"required"`
	PartyID         string                `json:"party_id" validate:"required,len=3"`
	CountryCode     string                `json:"country_code" validate:"required,len=2"`
}
