openapi: 3.1.0
info:
  title: OCPI 2.2.1 - Commands Module - Receiver Interface
  description: |
    The Receiver Interface is typically implemented by market roles like the CPO.
    It enables a Sender (typically eMSP) to send commands to a Location/EVSE.

    The commands module is designed to work asynchronously. The Receiver checks if it can send
    the request to a Charge Point and responds with a status indicating if the request can be sent.
    The actual result from the Charge Point is sent asynchronously via a POST to the Sender interface.

    Endpoint structure: {commands_endpoint_url}/{command}
  version: 2.2.1
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.2.1 Specification
  url: https://github.com/ocpi/ocpi/blob/master/mod_commands.asciidoc
security:
  - ocpiAuthorization: []
components:
  securitySchemes:
    ocpiAuthorization:
      $ref: "../../components/schema.yaml#/components/securitySchemes/ocpiAuthorization"

paths:
  /commands/CANCEL_RESERVATION:
    post:
      operationId: receiverPostCancelReservation
      summary: Send a CANCEL_RESERVATION command
      description: |
        Request the Charge Point to cancel a specific reservation.
        The response contains the direct response from the CPO, not from the Charge Point.
        The Charge Point result will be sent asynchronously via POST to the response_url.
      tags: [ Commands ]
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: CancelReservation object with information needed to cancel an existing reservation.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/CancelReservation"
      responses:
        "200":
          description: The command request was received by the CPO.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/CommandResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

  /commands/RESERVE_NOW:
    post:
      operationId: receiverPostReserveNow
      summary: Send a RESERVE_NOW command
      description: |
        Request the Charge Point to reserve a (specific) EVSE for a Token for a certain time, starting now.
        The response contains the direct response from the CPO, not from the Charge Point.
        The Charge Point result will be sent asynchronously via POST to the response_url.
      tags: [ Commands ]
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: ReserveNow object with information needed to reserve a (specific) connector of a Charge Point for a given Token.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/ReserveNow"
      responses:
        "200":
          description: The command request was received by the CPO.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/CommandResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

  /commands/START_SESSION:
    post:
      operationId: receiverPostStartSession
      summary: Send a START_SESSION command
      description: |
        Request the Charge Point to start a transaction on the given EVSE/Connector.
        The response contains the direct response from the CPO, not from the Charge Point.
        The Charge Point result will be sent asynchronously via POST to the response_url.
      tags: [ Commands ]
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: StartSession object with information needed to start a session.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/StartSession"
      responses:
        "200":
          description: The command request was received by the CPO.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/CommandResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

  /commands/STOP_SESSION:
    post:
      operationId: receiverPostStopSession
      summary: Send a STOP_SESSION command
      description: |
        Request the Charge Point to stop an ongoing session.
        The response contains the direct response from the CPO, not from the Charge Point.
        The Charge Point result will be sent asynchronously via POST to the response_url.
      tags: [ Commands ]
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: StopSession object with information needed to stop a session.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/StopSession"
      responses:
        "200":
          description: The command request was received by the CPO.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/CommandResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

  /commands/UNLOCK_CONNECTOR:
    post:
      operationId: receiverPostUnlockConnector
      summary: Send an UNLOCK_CONNECTOR command
      description: |
        Request the Charge Point to unlock the connector (if applicable).
        This functionality is for help desk operators only!
        The UNLOCK_CONNECTOR command may only be used by an operator or the eMSP.
        This command SHALL never be allowed to be sent directly by the EV-Driver.

        The response contains the direct response from the CPO, not from the Charge Point.
        The Charge Point result will be sent asynchronously via POST to the response_url.
      tags: [ Commands ]
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: UnlockConnector object with information needed to unlock a connector of a Charge Point.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/UnlockConnector"
      responses:
        "200":
          description: The command request was received by the CPO.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/CommandResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"