openapi: 3.1.0
info:
  title: OCPI 2.3.0 - Bookings Module - Sender Interface
  description: |
    The Sender Interface is implemented by the CPO. It allows the eMSP to fetch
    BookingLocation and Calendar data, and to retrieve the list of Bookings. The eMSP can
    also create new Bookings via the POST endpoint.
  version: 2.3.0
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.3.0 Specification
  url: https://github.com/ocpi/ocpi/blob/master/mod_bookings.asciidoc
security:
  - ocpiAuthorization: []
components:
  securitySchemes:
    ocpiAuthorization:
      $ref: "../../components/schema.yaml#/components/securitySchemes/ocpiAuthorization"

paths:
  /bookings/booking_locations:
    get:
      operationId: senderGetBookingLocations
      summary: Get list of BookingLocations
      tags: [ Bookings ]
      description: |
        Fetch a paginated list of BookingLocation objects. If date_from and/or date_to are
        provided, only BookingLocations with last_updated between the given date_from
        (including) and date_to (excluding) will be returned.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/DateFromParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/DateToParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/OffsetParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/LimitParameter"
        - $ref: "./parameters.yaml#/components/parameters/TimeslotFromParameter"
        - $ref: "./parameters.yaml#/components/parameters/TimeslotToParameter"
      responses:
        "200":
          description: Successful response containing a list of BookingLocation objects.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
            X-Total-Count:
              $ref: "../../components/schema.yaml#/components/headers/X-Total-Count"
            X-Limit:
              $ref: "../../components/schema.yaml#/components/headers/X-Limit"
            Link:
              $ref: "../../components/schema.yaml#/components/headers/Link"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "./schema.yaml#/components/schemas/BookingLocation"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

  /bookings/booking_locations/{booking_location_id}:
    get:
      operationId: senderGetBookingLocation
      summary: Get a BookingLocation
      tags: [ Bookings ]
      description: Retrieve a specific BookingLocation object by its booking_location_id.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "./parameters.yaml#/components/parameters/BookingLocationIdParameter"
      responses:
        "200":
          description: Successful response containing the requested BookingLocation object.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/BookingLocation"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"

  /bookings/booking_locations/{booking_location_id}/{calendar_id}:
    get:
      operationId: senderGetCalendar
      summary: Get a Calendar
      tags: [ Bookings ]
      description: Retrieve a specific Calendar object by its booking_location_id and calendar_id.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "./parameters.yaml#/components/parameters/BookingLocationIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/CalendarIdParameter"
      responses:
        "200":
          description: Successful response containing the requested Calendar object.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/Calendar"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"

  /bookings:
    get:
      operationId: senderGetBookings
      summary: Get list of Bookings
      tags: [ Bookings ]
      description: |
        Fetch a paginated list of Booking objects. If date_from and/or date_to are provided,
        only Bookings with last_updated between the given date_from (including) and date_to
        (excluding) will be returned.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/DateFromParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/DateToParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/OffsetParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/LimitParameter"
      responses:
        "200":
          description: Successful response containing a list of Booking objects.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
            X-Total-Count:
              $ref: "../../components/schema.yaml#/components/headers/X-Total-Count"
            X-Limit:
              $ref: "../../components/schema.yaml#/components/headers/X-Limit"
            Link:
              $ref: "../../components/schema.yaml#/components/headers/Link"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "./schema.yaml#/components/schemas/Booking"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

    post:
      operationId: senderPostBooking
      summary: Create a new Booking
      tags: [ Bookings ]
      description: |
        Create a new Booking. The request body is a BookingRequest. The response contains
        the created Booking object.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
      requestBody:
        description: BookingRequest object to create a new Booking.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/BookingRequest"
      responses:
        "200":
          description: Successful response containing the created Booking object.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/Booking"
        "201":
          description: Booking successfully created.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/Booking"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
