// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"github.com/shopspring/decimal"
	"time"
)

// CDR: The CDR object describes the charging session and its costs, how these costs are composed, etc.
// The CDR can be thought of as sealed, preserving the information valid at the moment in time
// the underlying session was started. This is a requirement of the main use case for CDRs, namely invoicing.
// The CDR object shall always contain information like Location, EVSE, Tariffs and Token
// as they were at the start of the charging session.
type CDR struct {
	CountryCode              string           `json:"country_code" validate:"required,len=2"`
	PartyID                  string           `json:"party_id" validate:"required,len=3"`
	ID                       string           `json:"id" validate:"required,max=39"`
	StartDateTime            time.Time        `json:"start_date_time" validate:"required"`
	EndDateTime              time.Time        `json:"end_date_time" validate:"required"`
	SessionID                *string          `json:"session_id,omitempty" validate:"omitempty,max=36"`
	CDRToken                 CdrToken         `json:"cdr_token" validate:"required"`
	AuthMethod               AuthMethod       `json:"auth_method" validate:"required"`
	AuthorizationReference   *string          `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	CDRLocation              CdrLocation      `json:"cdr_location" validate:"required"`
	MeterID                  *string          `json:"meter_id,omitempty" validate:"omitempty,max=255"`
	Currency                 string           `json:"currency" validate:"required,len=3"`
	Tariffs                  []Tariff         `json:"tariffs,omitempty"`
	ChargingPeriods          []ChargingPeriod `json:"charging_periods" validate:"required,min=1"`
	SignedData               *SignedData      `json:"signed_data,omitempty"`
	TotalCost                Price            `json:"total_cost" validate:"required"`
	TotalFixedCost           *Price           `json:"total_fixed_cost,omitempty"`
	TotalEnergy              decimal.Decimal  `json:"total_energy" validate:"required"`
	TotalEnergyCost          *Price           `json:"total_energy_cost,omitempty"`
	TotalTime                decimal.Decimal  `json:"total_time" validate:"required"`
	TotalTimeCost            *Price           `json:"total_time_cost,omitempty"`
	TotalParkingTime         *decimal.Decimal `json:"total_parking_time,omitempty"`
	TotalParkingCost         *Price           `json:"total_parking_cost,omitempty"`
	TotalReservationCost     *Price           `json:"total_reservation_cost,omitempty"`
	Remark                   *string          `json:"remark,omitempty" validate:"omitempty,max=255"`
	InvoiceReferenceID       *string          `json:"invoice_reference_id,omitempty" validate:"omitempty,max=39"`
	Credit                   *bool            `json:"credit,omitempty"`
	CreditReferenceID        *string          `json:"credit_reference_id,omitempty" validate:"omitempty,max=39"`
	HomeChargingCompensation *bool            `json:"home_charging_compensation,omitempty"`
	LastUpdated              time.Time        `json:"last_updated" validate:"required"`
}

// CdrLocation: The CdrLocation class contains only the relevant information from the Location object
// that is needed in a CDR.
type CdrLocation struct {
	ID                 string          `json:"id" validate:"required,max=36"`
	Name               *string         `json:"name,omitempty" validate:"omitempty,max=255"`
	Address            string          `json:"address" validate:"required,max=45"`
	City               string          `json:"city" validate:"required,max=45"`
	PostalCode         *string         `json:"postal_code,omitempty" validate:"omitempty,max=10"`
	State              *string         `json:"state,omitempty" validate:"omitempty,max=20"`
	Country            string          `json:"country" validate:"required,len=3"`
	Coordinates        GeoLocation     `json:"coordinates" validate:"required"`
	EVSEUID            string          `json:"evse_uid" validate:"required,max=36"`
	EVSEID             string          `json:"evse_id" validate:"required,max=48"`
	ConnectorID        string          `json:"connector_id" validate:"required,max=36"`
	ConnectorStandard  ConnectorType   `json:"connector_standard" validate:"required"`
	ConnectorFormat    ConnectorFormat `json:"connector_format" validate:"required"`
	ConnectorPowerType PowerType       `json:"connector_power_type" validate:"required"`
}

// CdrToken: Token information used to start a charging session, containing all relevant information to identify the unique token.
type CdrToken struct {
	CountryCode string    `json:"country_code" validate:"required,len=2"`
	PartyID     string    `json:"party_id" validate:"required,len=3"`
	UID         string    `json:"uid" validate:"required,max=36"`
	Type        TokenType `json:"type" validate:"required"`
	ContractID  string    `json:"contract_id" validate:"required,max=36"`
}

// ChargingPeriod: A Charging Period consists of a start timestamp and a list of possible values that influence
// this period, for example: amount of energy charged this period, maximum current during this
// period etc.
type ChargingPeriod struct {
	StartDateTime time.Time      `json:"start_date_time" validate:"required"`
	Dimensions    []CdrDimension `json:"dimensions" validate:"required,min=1"`
	TariffID      *string        `json:"tariff_id,omitempty" validate:"omitempty,max=36"`
}

// CdrDimension: A dimension value for a charging period.
type CdrDimension struct {
	Type   CdrDimensionType `json:"type" validate:"required"`
	Volume decimal.Decimal  `json:"volume" validate:"required"`
}

// SignedData: This class contains all the information of the signed data. Which encoding method is used,
// if needed, the public key and a list of signed values.
type SignedData struct {
	EncodingMethod        string        `json:"encoding_method" validate:"required,max=36"`
	EncodingMethodVersion *int          `json:"encoding_method_version,omitempty"`
	PublicKey             *string       `json:"public_key,omitempty" validate:"omitempty,max=512"`
	SignedValues          []SignedValue `json:"signed_values" validate:"required,min=1"`
	URL                   *string       `json:"url,omitempty" validate:"omitempty,max=512"`
}

// SignedValue: This class contains the signed and the plain/unsigned data.
// By decoding the data, the receiver can check if the content has not been altered.
type SignedValue struct {
	Nature     string `json:"nature" validate:"required,max=32"`
	PlainData  string `json:"plain_data" validate:"required,max=512"`
	SignedData string `json:"signed_data" validate:"required,max=5000"`
}

// AuthMethod: Method used for authentication.
type AuthMethod string

const (
	AuthMethodAuthRequest AuthMethod = "AUTH_REQUEST"
	AuthMethodCommand     AuthMethod = "COMMAND"
	AuthMethodWhitelist   AuthMethod = "WHITELIST"
)

// CdrDimensionType: Defines the type of a CDR dimension. Some of these values are not useful for CDRs,
// and SHALL therefore only be used in Sessions (marked as Session Only).
type CdrDimensionType string

const (
	CdrDimensionTypeCurrent         CdrDimensionType = "CURRENT"
	CdrDimensionTypeEnergy          CdrDimensionType = "ENERGY"
	CdrDimensionTypeEnergyExport    CdrDimensionType = "ENERGY_EXPORT"
	CdrDimensionTypeEnergyImport    CdrDimensionType = "ENERGY_IMPORT"
	CdrDimensionTypeMaxCurrent      CdrDimensionType = "MAX_CURRENT"
	CdrDimensionTypeMinCurrent      CdrDimensionType = "MIN_CURRENT"
	CdrDimensionTypeMaxPower        CdrDimensionType = "MAX_POWER"
	CdrDimensionTypeMinPower        CdrDimensionType = "MIN_POWER"
	CdrDimensionTypeParkingTime     CdrDimensionType = "PARKING_TIME"
	CdrDimensionTypePower           CdrDimensionType = "POWER"
	CdrDimensionTypeReservationTime CdrDimensionType = "RESERVATION_TIME"
	CdrDimensionTypeStateOfCharge   CdrDimensionType = "STATE_OF_CHARGE"
	CdrDimensionTypeTime            CdrDimensionType = "TIME"
)
