// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// ChargingprofilesSenderClient calls the Chargingprofiles sender interface on a peer.
type ChargingprofilesSenderClient struct {
	c    *core.Client
	base string
}

// NewChargingprofilesSenderClient binds a client to baseURL (the peer's chargingprofiles endpoint URL).
func NewChargingprofilesSenderClient(c *core.Client, baseURL string) *ChargingprofilesSenderClient {
	return &ChargingprofilesSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *ChargingprofilesSenderClient) PostChargingProfileCallback(ctx context.Context) error {
	u := x.base + "/" + "response"
	resp, err := x.c.Do(ctx, http.MethodPost, u, nil)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *ChargingprofilesSenderClient) PutActiveChargingProfile(ctx context.Context, sessionID string, body ActiveChargingProfile) error {
	u := x.base + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// ChargingprofilesSenderHandler handles inbound Chargingprofiles sender requests.
type ChargingprofilesSenderHandler interface {
	PostChargingProfileCallback(ctx context.Context) *status.Error
	PutActiveChargingProfile(ctx context.Context, sessionID string, body ActiveChargingProfile) *status.Error
}

// RegisterChargingprofilesSender registers h's routes on mux under basePath (the module mount path).
func RegisterChargingprofilesSender(mux *core.Mux, basePath string, h ChargingprofilesSenderHandler) {
	base := strings.TrimRight(basePath, "/")
	mux.Handle(http.MethodPost, base+"/response", func(w http.ResponseWriter, r *http.Request) {
		if herr := h.PostChargingProfileCallback(r.Context()); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		var body ActiveChargingProfile
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutActiveChargingProfile(r.Context(), r.PathValue("session_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
