// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"github.com/shopspring/decimal"
	"time"
)

// SetChargingProfile: Object sent to a CPO to set a Charging Profile.
type SetChargingProfile struct {
	ChargingProfile ChargingProfile `json:"charging_profile" validate:"required"`
	ResponseURL     string          `json:"response_url" validate:"required"`
}

// ChargingProfileResponse: The ChargingProfileResponse object is send in the HTTP response body.
type ChargingProfileResponse struct {
	Result  ChargingProfileResponseType `json:"result" validate:"required"`
	Timeout int                         `json:"timeout" validate:"required"`
}

// ActiveChargingProfileResult: The ActiveChargingProfileResult object is send by the CPO to the given response_url in a POST request.
// It contains the result of the GET (ActiveChargingProfile) request send by the eMSP.
type ActiveChargingProfileResult struct {
	Result  ChargingProfileResultType `json:"result" validate:"required"`
	Profile *ActiveChargingProfile    `json:"profile,omitempty"`
}

// ChargingProfileResult: The ChargingProfileResult object is sent by the CPO to the given response_url in a POST request.
// It contains the result of the PUT (SetChargingProfile) request sent by the eMSP.
type ChargingProfileResult struct {
	Result ChargingProfileResultType `json:"result" validate:"required"`
}

// ClearProfileResult: The ClearProfileResult object is sent by the CPO to the given response_url in a POST request.
// It contains the result of the DELETE (ClearProfile) request sent by the eMSP.
type ClearProfileResult struct {
	Result ChargingProfileResultType `json:"result" validate:"required"`
}

// ActiveChargingProfile: The ActiveChargingProfile is the charging profile as calculated by the EVSE.
type ActiveChargingProfile struct {
	StartDateTime   time.Time       `json:"start_date_time" validate:"required"`
	ChargingProfile ChargingProfile `json:"charging_profile" validate:"required"`
}

// ChargingProfile: Charging profile class defines a list of charging periods.
type ChargingProfile struct {
	StartDateTime         *time.Time              `json:"start_date_time,omitempty"`
	Duration              *int                    `json:"duration,omitempty"`
	ChargingRateUnit      ChargingRateUnit        `json:"charging_rate_unit" validate:"required"`
	MinChargingRate       *decimal.Decimal        `json:"min_charging_rate,omitempty"`
	ChargingProfilePeriod []ChargingProfilePeriod `json:"charging_profile_period,omitempty"`
}

// ChargingProfilePeriod: Charging profile period structure defines a time period in a charging profile, as used in: ChargingProfile
type ChargingProfilePeriod struct {
	StartPeriod int             `json:"start_period" validate:"required"`
	Limit       decimal.Decimal `json:"limit" validate:"required"`
}

// ChargingRateUnit: Unit in which a charging profile is defined.
type ChargingRateUnit string

const (
	ChargingRateUnitW ChargingRateUnit = "W"
	ChargingRateUnitA ChargingRateUnit = "A"
)

// ChargingProfileResponseType: Response to the ChargingProfile request from the eMSP to the CPO.
type ChargingProfileResponseType string

const (
	ChargingProfileResponseTypeAccepted       ChargingProfileResponseType = "ACCEPTED"
	ChargingProfileResponseTypeNotSupported   ChargingProfileResponseType = "NOT_SUPPORTED"
	ChargingProfileResponseTypeRejected       ChargingProfileResponseType = "REJECTED"
	ChargingProfileResponseTypeTooOften       ChargingProfileResponseType = "TOO_OFTEN"
	ChargingProfileResponseTypeUnknownSession ChargingProfileResponseType = "UNKNOWN_SESSION"
)

// ChargingProfileResultType: Result of a ChargingProfile request that the EVSE sends via the CPO to the eMSP.
type ChargingProfileResultType string

const (
	ChargingProfileResultTypeAccepted ChargingProfileResultType = "ACCEPTED"
	ChargingProfileResultTypeRejected ChargingProfileResultType = "REJECTED"
	ChargingProfileResultTypeUnknown  ChargingProfileResultType = "UNKNOWN"
)
