// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// CommandsReceiverClient calls the Commands receiver interface on a peer.
type CommandsReceiverClient struct {
	c    *core.Client
	base string
}

// NewCommandsReceiverClient binds a client to baseURL (the peer's commands endpoint URL).
func NewCommandsReceiverClient(c *core.Client, baseURL string) *CommandsReceiverClient {
	return &CommandsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *CommandsReceiverClient) PostCancelReservation(ctx context.Context, body CancelReservation) (CommandResponse, error) {
	u := x.base + "/" + "CANCEL_RESERVATION"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero CommandResponse
		return zero, err
	}
	out, err := core.Decode[CommandResponse](resp)
	return out.Data, err
}

func (x *CommandsReceiverClient) PostReserveNow(ctx context.Context, body ReserveNow) (CommandResponse, error) {
	u := x.base + "/" + "RESERVE_NOW"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero CommandResponse
		return zero, err
	}
	out, err := core.Decode[CommandResponse](resp)
	return out.Data, err
}

func (x *CommandsReceiverClient) PostStartSession(ctx context.Context, body StartSession) (CommandResponse, error) {
	u := x.base + "/" + "START_SESSION"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero CommandResponse
		return zero, err
	}
	out, err := core.Decode[CommandResponse](resp)
	return out.Data, err
}

func (x *CommandsReceiverClient) PostStopSession(ctx context.Context, body StopSession) (CommandResponse, error) {
	u := x.base + "/" + "STOP_SESSION"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero CommandResponse
		return zero, err
	}
	out, err := core.Decode[CommandResponse](resp)
	return out.Data, err
}

func (x *CommandsReceiverClient) PostUnlockConnector(ctx context.Context, body UnlockConnector) (CommandResponse, error) {
	u := x.base + "/" + "UNLOCK_CONNECTOR"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero CommandResponse
		return zero, err
	}
	out, err := core.Decode[CommandResponse](resp)
	return out.Data, err
}

// CommandsReceiverHandler handles inbound Commands receiver requests.
type CommandsReceiverHandler interface {
	PostCancelReservation(ctx context.Context, body CancelReservation) (CommandResponse, *status.Error)
	PostReserveNow(ctx context.Context, body ReserveNow) (CommandResponse, *status.Error)
	PostStartSession(ctx context.Context, body StartSession) (CommandResponse, *status.Error)
	PostStopSession(ctx context.Context, body StopSession) (CommandResponse, *status.Error)
	PostUnlockConnector(ctx context.Context, body UnlockConnector) (CommandResponse, *status.Error)
}

// RegisterCommandsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterCommandsReceiver(mux *core.Mux, basePath string, h CommandsReceiverHandler) {
	base := strings.TrimRight(basePath, "/")
	mux.Handle(http.MethodPost, base+"/CANCEL_RESERVATION", func(w http.ResponseWriter, r *http.Request) {
		var body CancelReservation
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostCancelReservation(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/RESERVE_NOW", func(w http.ResponseWriter, r *http.Request) {
		var body ReserveNow
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostReserveNow(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/START_SESSION", func(w http.ResponseWriter, r *http.Request) {
		var body StartSession
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostStartSession(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/STOP_SESSION", func(w http.ResponseWriter, r *http.Request) {
		var body StopSession
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostStopSession(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/UNLOCK_CONNECTOR", func(w http.ResponseWriter, r *http.Request) {
		var body UnlockConnector
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostUnlockConnector(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
