// Code generated by gocpi codegen. DO NOT EDIT.

// Package v221 contains the generated OCPI 2.2.1 types, typed Sender/Receiver clients,
// server handler interfaces, role presets (RegisterCPO/RegisterMSP/RegisterHub)
// and an embedded JSON-Schema validator. All of a version's types live in this
// single package because OCPI modules reference each other's schemas cyclically.
package v221
