// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"net/http"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// HubclientinfoSenderClient calls the Hubclientinfo sender interface on a peer.
type HubclientinfoSenderClient struct {
	c    *core.Client
	base string
}

// NewHubclientinfoSenderClient binds a client to baseURL (the peer's hubclientinfo endpoint URL).
func NewHubclientinfoSenderClient(c *core.Client, baseURL string) *HubclientinfoSenderClient {
	return &HubclientinfoSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *HubclientinfoSenderClient) GetClientInfoList(ctx context.Context, p core.PageOpts) (core.Page[ClientInfo], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[ClientInfo]{}, err
	}
	out, err := core.Decode[[]ClientInfo](resp)
	if err != nil {
		return core.Page[ClientInfo]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[ClientInfo]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

// HubclientinfoSenderHandler handles inbound Hubclientinfo sender requests.
type HubclientinfoSenderHandler interface {
	GetClientInfoList(ctx context.Context, req core.PageReq) (core.Page[ClientInfo], *status.Error)
}

// RegisterHubclientinfoSender registers h's routes on mux under basePath (the module mount path).
func RegisterHubclientinfoSender(mux *core.Mux, basePath string, h HubclientinfoSenderHandler) {
	base := strings.TrimRight(basePath, "/")
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetClientInfoList(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
}
