// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// HubclientinfoReceiverClient calls the Hubclientinfo receiver interface on a peer.
type HubclientinfoReceiverClient struct {
	c    *core.Client
	base string
}

// NewHubclientinfoReceiverClient binds a client to baseURL (the peer's hubclientinfo endpoint URL).
func NewHubclientinfoReceiverClient(c *core.Client, baseURL string) *HubclientinfoReceiverClient {
	return &HubclientinfoReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *HubclientinfoReceiverClient) GetClientInfo(ctx context.Context, countryCode string, partyID string) (ClientInfo, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero ClientInfo
		return zero, err
	}
	out, err := core.Decode[ClientInfo](resp)
	return out.Data, err
}

func (x *HubclientinfoReceiverClient) PutClientInfo(ctx context.Context, countryCode string, partyID string, body ClientInfo) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// HubclientinfoReceiverHandler handles inbound Hubclientinfo receiver requests.
type HubclientinfoReceiverHandler interface {
	GetClientInfo(ctx context.Context, countryCode string, partyID string) (ClientInfo, *status.Error)
	PutClientInfo(ctx context.Context, countryCode string, partyID string, body ClientInfo) *status.Error
}

// RegisterHubclientinfoReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterHubclientinfoReceiver(mux *core.Mux, basePath string, h HubclientinfoReceiverHandler) {
	base := strings.TrimRight(basePath, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetClientInfo(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}", func(w http.ResponseWriter, r *http.Request) {
		var body ClientInfo
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutClientInfo(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
