// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// LocationsReceiverClient calls the Locations receiver interface on a peer.
type LocationsReceiverClient struct {
	c    *core.Client
	base string
}

// NewLocationsReceiverClient binds a client to baseURL (the peer's locations endpoint URL).
func NewLocationsReceiverClient(c *core.Client, baseURL string) *LocationsReceiverClient {
	return &LocationsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *LocationsReceiverClient) GetLocation(ctx context.Context, countryCode string, partyID string, locationID string) (Location, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Location
		return zero, err
	}
	out, err := core.Decode[Location](resp)
	return out.Data, err
}

func (x *LocationsReceiverClient) PutLocation(ctx context.Context, countryCode string, partyID string, locationID string, body Location) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *LocationsReceiverClient) PatchLocation(ctx context.Context, countryCode string, partyID string, locationID string, body LocationPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *LocationsReceiverClient) GetEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string) (EVSE, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero EVSE
		return zero, err
	}
	out, err := core.Decode[EVSE](resp)
	return out.Data, err
}

func (x *LocationsReceiverClient) PutEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, body EVSE) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *LocationsReceiverClient) PatchEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, body EVSEPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *LocationsReceiverClient) GetConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string) (Connector, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID) + "/" + url.PathEscape(connectorID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Connector
		return zero, err
	}
	out, err := core.Decode[Connector](resp)
	return out.Data, err
}

func (x *LocationsReceiverClient) PutConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string, body Connector) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID) + "/" + url.PathEscape(connectorID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *LocationsReceiverClient) PatchConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string, body ConnectorPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID) + "/" + url.PathEscape(connectorID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// LocationsReceiverHandler handles inbound Locations receiver requests.
type LocationsReceiverHandler interface {
	GetLocation(ctx context.Context, countryCode string, partyID string, locationID string) (Location, *status.Error)
	PutLocation(ctx context.Context, countryCode string, partyID string, locationID string, body Location) *status.Error
	PatchLocation(ctx context.Context, countryCode string, partyID string, locationID string, body LocationPatch) *status.Error
	GetEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string) (EVSE, *status.Error)
	PutEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, body EVSE) *status.Error
	PatchEvse(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, body EVSEPatch) *status.Error
	GetConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string) (Connector, *status.Error)
	PutConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string, body Connector) *status.Error
	PatchConnector(ctx context.Context, countryCode string, partyID string, locationID string, eVSEUID string, connectorID string, body ConnectorPatch) *status.Error
}

// RegisterLocationsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterLocationsReceiver(mux *core.Mux, basePath string, h LocationsReceiverHandler) {
	base := strings.TrimRight(basePath, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{location_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{location_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Location
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{location_id}", func(w http.ResponseWriter, r *http.Request) {
		var body LocationPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetEvse(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}", func(w http.ResponseWriter, r *http.Request) {
		var body EVSE
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutEvse(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}", func(w http.ResponseWriter, r *http.Request) {
		var body EVSEPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchEvse(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}/{connector_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetConnector(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"), r.PathValue("connector_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}/{connector_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Connector
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutConnector(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"), r.PathValue("connector_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{location_id}/{evse_uid}/{connector_id}", func(w http.ResponseWriter, r *http.Request) {
		var body ConnectorPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchConnector(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("location_id"), r.PathValue("evse_uid"), r.PathValue("connector_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
