// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// LocationsSenderClient calls the Locations sender interface on a peer.
type LocationsSenderClient struct {
	c    *core.Client
	base string
}

// NewLocationsSenderClient binds a client to baseURL (the peer's locations endpoint URL).
func NewLocationsSenderClient(c *core.Client, baseURL string) *LocationsSenderClient {
	return &LocationsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *LocationsSenderClient) GetLocations(ctx context.Context, p core.PageOpts) (core.Page[Location], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[Location]{}, err
	}
	out, err := core.Decode[[]Location](resp)
	if err != nil {
		return core.Page[Location]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[Location]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *LocationsSenderClient) GetLocation(ctx context.Context, locationID string) (Location, error) {
	u := x.base + "/" + url.PathEscape(locationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Location
		return zero, err
	}
	out, err := core.Decode[Location](resp)
	return out.Data, err
}

func (x *LocationsSenderClient) GetEvse(ctx context.Context, locationID string, eVSEUID string) (EVSE, error) {
	u := x.base + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero EVSE
		return zero, err
	}
	out, err := core.Decode[EVSE](resp)
	return out.Data, err
}

func (x *LocationsSenderClient) GetConnector(ctx context.Context, locationID string, eVSEUID string, connectorID string) (Connector, error) {
	u := x.base + "/" + url.PathEscape(locationID) + "/" + url.PathEscape(eVSEUID) + "/" + url.PathEscape(connectorID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Connector
		return zero, err
	}
	out, err := core.Decode[Connector](resp)
	return out.Data, err
}

// LocationsSenderHandler handles inbound Locations sender requests.
type LocationsSenderHandler interface {
	GetLocations(ctx context.Context, req core.PageReq) (core.Page[Location], *status.Error)
	GetLocation(ctx context.Context, locationID string) (Location, *status.Error)
	GetEvse(ctx context.Context, locationID string, eVSEUID string) (EVSE, *status.Error)
	GetConnector(ctx context.Context, locationID string, eVSEUID string, connectorID string) (Connector, *status.Error)
}

// RegisterLocationsSender registers h's routes on mux under basePath (the module mount path).
func RegisterLocationsSender(mux *core.Mux, basePath string, h LocationsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetLocations(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{location_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetLocation(r.Context(), r.PathValue("location_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{location_id}/{evse_uid}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetEvse(r.Context(), r.PathValue("location_id"), r.PathValue("evse_uid"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{location_id}/{evse_uid}/{connector_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetConnector(r.Context(), r.PathValue("location_id"), r.PathValue("evse_uid"), r.PathValue("connector_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
