// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// SessionsSenderClient calls the Sessions sender interface on a peer.
type SessionsSenderClient struct {
	c    *core.Client
	base string
}

// NewSessionsSenderClient binds a client to baseURL (the peer's sessions endpoint URL).
func NewSessionsSenderClient(c *core.Client, baseURL string) *SessionsSenderClient {
	return &SessionsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *SessionsSenderClient) GetSessions(ctx context.Context, p core.PageOpts) (core.Page[Session], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[Session]{}, err
	}
	out, err := core.Decode[[]Session](resp)
	if err != nil {
		return core.Page[Session]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[Session]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *SessionsSenderClient) PutChargingPreferences(ctx context.Context, sessionID string, body ChargingPreferences) (ChargingPreferencesResponse, error) {
	u := x.base + "/" + url.PathEscape(sessionID) + "/" + "charging_preferences"
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		var zero ChargingPreferencesResponse
		return zero, err
	}
	out, err := core.Decode[ChargingPreferencesResponse](resp)
	return out.Data, err
}

// SessionsSenderHandler handles inbound Sessions sender requests.
type SessionsSenderHandler interface {
	GetSessions(ctx context.Context, req core.PageReq) (core.Page[Session], *status.Error)
	PutChargingPreferences(ctx context.Context, sessionID string, body ChargingPreferences) (ChargingPreferencesResponse, *status.Error)
}

// RegisterSessionsSender registers h's routes on mux under basePath (the module mount path).
func RegisterSessionsSender(mux *core.Mux, basePath string, h SessionsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetSessions(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{session_id}/charging_preferences", func(w http.ResponseWriter, r *http.Request) {
		var body ChargingPreferences
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PutChargingPreferences(r.Context(), r.PathValue("session_id"), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
