// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// TariffsReceiverClient calls the Tariffs receiver interface on a peer.
type TariffsReceiverClient struct {
	c    *core.Client
	base string
}

// NewTariffsReceiverClient binds a client to baseURL (the peer's tariffs endpoint URL).
func NewTariffsReceiverClient(c *core.Client, baseURL string) *TariffsReceiverClient {
	return &TariffsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *TariffsReceiverClient) GetTariff(ctx context.Context, countryCode string, partyID string, tariffID string) (Tariff, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tariffID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Tariff
		return zero, err
	}
	out, err := core.Decode[Tariff](resp)
	return out.Data, err
}

func (x *TariffsReceiverClient) PutTariff(ctx context.Context, countryCode string, partyID string, tariffID string, body Tariff) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tariffID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *TariffsReceiverClient) DeleteTariff(ctx context.Context, countryCode string, partyID string, tariffID string) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(tariffID)
	resp, err := x.c.Do(ctx, http.MethodDelete, u, nil)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// TariffsReceiverHandler handles inbound Tariffs receiver requests.
type TariffsReceiverHandler interface {
	GetTariff(ctx context.Context, countryCode string, partyID string, tariffID string) (Tariff, *status.Error)
	PutTariff(ctx context.Context, countryCode string, partyID string, tariffID string, body Tariff) *status.Error
	DeleteTariff(ctx context.Context, countryCode string, partyID string, tariffID string) *status.Error
}

// RegisterTariffsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterTariffsReceiver(mux *core.Mux, basePath string, h TariffsReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{tariff_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetTariff(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("tariff_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{tariff_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Tariff
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutTariff(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("tariff_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodDelete, base+"/{country_code}/{party_id}/{tariff_id}", func(w http.ResponseWriter, r *http.Request) {
		if herr := h.DeleteTariff(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("tariff_id")); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
