// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"github.com/shopspring/decimal"
	"time"
)

// Tariff: A Tariff object consists of a list of one or more Tariff Elements, which in turn consist of
// Price Components. A Tariff Element is a group of Price Components that apply under the same
// conditions. The rules for the conditions under which a Tariff Element applies are known as
// its "restrictions". A Price Component describes how the usage of a particular dimension
// (time, energy, etcetera) is mapped to an amount of money owed.
// When the list of Tariff Elements contains more than one Element that has a Price Component
// for a certain dimension, then the first Tariff Element with a Price Component for that
// dimension in the list with matching Tariff Restrictions will be used.
// To define a "Free of Charge" tariff in OCPI, a Tariff containing one Tariff Element with
// no restrictions containing one Price Component with type = FLAT and price = 0.00 has to
// be provided.
type Tariff struct {
	CountryCode   string          `json:"country_code" validate:"required,len=2"`
	PartyID       string          `json:"party_id" validate:"required,len=3"`
	ID            string          `json:"id" validate:"required,max=36"`
	Currency      string          `json:"currency" validate:"required,len=3"`
	Type          *TariffType     `json:"type,omitempty"`
	TariffAltText []DisplayText   `json:"tariff_alt_text,omitempty"`
	TariffAltURL  *string         `json:"tariff_alt_url,omitempty"`
	MinPrice      *Price          `json:"min_price,omitempty"`
	MaxPrice      *Price          `json:"max_price,omitempty"`
	Elements      []TariffElement `json:"elements" validate:"required,min=1"`
	StartDateTime *time.Time      `json:"start_date_time,omitempty"`
	EndDateTime   *time.Time      `json:"end_date_time,omitempty"`
	EnergyMix     *EnergyMix      `json:"energy_mix,omitempty"`
	LastUpdated   time.Time       `json:"last_updated" validate:"required"`
}

// TariffElement: A Tariff Element is a group of Price Components that share a set of restrictions under
// which they apply. That the Price Components share the same restrictions does not mean that
// at any time, they either all apply or all do not apply. Applicable Price Components are
// looked up separately for each dimension.
type TariffElement struct {
	PriceComponents []PriceComponent    `json:"price_components" validate:"required,min=1"`
	Restrictions    *TariffRestrictions `json:"restrictions,omitempty"`
}

// PriceComponent: A Price Component describes how a certain amount of a certain dimension being consumed translates into an amount of money owed.
type PriceComponent struct {
	Type     TariffDimensionType `json:"type" validate:"required"`
	Price    decimal.Decimal     `json:"price" validate:"required"`
	VAT      *decimal.Decimal    `json:"vat,omitempty"`
	StepSize int                 `json:"step_size" validate:"required"`
}

// TariffRestrictions: A TariffRestrictions object describes if and when a Tariff Element becomes active or
// inactive during a Charging Session. These restrictions are not to be interpreted as making
// the Tariff Element applicable or not applicable for the entire Charging Session. When more
// than one restriction is set, they are to be treated as a logical AND.
type TariffRestrictions struct {
	StartTime   *string                     `json:"start_time,omitempty"`
	EndTime     *string                     `json:"end_time,omitempty"`
	StartDate   *string                     `json:"start_date,omitempty"`
	EndDate     *string                     `json:"end_date,omitempty"`
	MinKwh      *decimal.Decimal            `json:"min_kwh,omitempty"`
	MaxKwh      *decimal.Decimal            `json:"max_kwh,omitempty"`
	MinCurrent  *decimal.Decimal            `json:"min_current,omitempty"`
	MaxCurrent  *decimal.Decimal            `json:"max_current,omitempty"`
	MinPower    *decimal.Decimal            `json:"min_power,omitempty"`
	MaxPower    *decimal.Decimal            `json:"max_power,omitempty"`
	MinDuration *int                        `json:"min_duration,omitempty"`
	MaxDuration *int                        `json:"max_duration,omitempty"`
	DayOfWeek   []DayOfWeek                 `json:"day_of_week,omitempty"`
	Reservation *ReservationRestrictionType `json:"reservation,omitempty"`
}

// TariffType: Type of tariff.
type TariffType string

const (
	TariffTypeAdHocPayment TariffType = "AD_HOC_PAYMENT"
	TariffTypeProfileCheap TariffType = "PROFILE_CHEAP"
	TariffTypeProfileFast  TariffType = "PROFILE_FAST"
	TariffTypeProfileGreen TariffType = "PROFILE_GREEN"
	TariffTypeRegular      TariffType = "REGULAR"
)

// TariffDimensionType: Defines the dimension of a tariff.
type TariffDimensionType string

const (
	TariffDimensionTypeEnergy      TariffDimensionType = "ENERGY"
	TariffDimensionTypeFlat        TariffDimensionType = "FLAT"
	TariffDimensionTypeParkingTime TariffDimensionType = "PARKING_TIME"
	TariffDimensionTypeTime        TariffDimensionType = "TIME"
)

// DayOfWeek: Day of the week.
type DayOfWeek string

const (
	DayOfWeekMonday    DayOfWeek = "MONDAY"
	DayOfWeekTuesday   DayOfWeek = "TUESDAY"
	DayOfWeekWednesday DayOfWeek = "WEDNESDAY"
	DayOfWeekThursday  DayOfWeek = "THURSDAY"
	DayOfWeekFriday    DayOfWeek = "FRIDAY"
	DayOfWeekSaturday  DayOfWeek = "SATURDAY"
	DayOfWeekSunday    DayOfWeek = "SUNDAY"
)

// ReservationRestrictionType: Defines if a TariffElement is applicable for a reservation.
type ReservationRestrictionType string

const (
	ReservationRestrictionTypeReservation        ReservationRestrictionType = "RESERVATION"
	ReservationRestrictionTypeReservationExpires ReservationRestrictionType = "RESERVATION_EXPIRES"
)
