// Code generated by gocpi codegen. DO NOT EDIT.

package v221

import (
	"time"
)

// Token: The Token object describes the token information of an eMSP. CPOs can use this to build
// a cache of known Tokens. When a request to authorize comes from a Charge Point, the CPO
// can check against this cache to know to which eMSP they can later send a CDR.
type Token struct {
	CountryCode        string          `json:"country_code" validate:"required,len=2"`
	PartyID            string          `json:"party_id" validate:"required,len=3"`
	UID                string          `json:"uid" validate:"required,max=36"`
	Type               TokenType       `json:"type" validate:"required"`
	ContractID         string          `json:"contract_id" validate:"required,max=36"`
	VisualNumber       *string         `json:"visual_number,omitempty" validate:"omitempty,max=64"`
	Issuer             string          `json:"issuer" validate:"required,max=64"`
	GroupID            *string         `json:"group_id,omitempty" validate:"omitempty,max=36"`
	Valid              bool            `json:"valid"`
	Whitelist          WhitelistType   `json:"whitelist" validate:"required"`
	Language           *string         `json:"language,omitempty" validate:"omitempty,len=2"`
	DefaultProfileType *ProfileType    `json:"default_profile_type,omitempty"`
	EnergyContract     *EnergyContract `json:"energy_contract,omitempty"`
	LastUpdated        time.Time       `json:"last_updated" validate:"required"`
}

// TokenPatch: Partial Token object for PATCH requests. Only fields present will be updated.
// The last_updated field is required.
type TokenPatch struct {
	CountryCode        *string         `json:"country_code,omitempty" validate:"omitempty,len=2"`
	PartyID            *string         `json:"party_id,omitempty" validate:"omitempty,len=3"`
	UID                *string         `json:"uid,omitempty" validate:"omitempty,max=36"`
	Type               *TokenType      `json:"type,omitempty"`
	ContractID         *string         `json:"contract_id,omitempty" validate:"omitempty,max=36"`
	VisualNumber       *string         `json:"visual_number,omitempty" validate:"omitempty,max=64"`
	Issuer             *string         `json:"issuer,omitempty" validate:"omitempty,max=64"`
	GroupID            *string         `json:"group_id,omitempty" validate:"omitempty,max=36"`
	Valid              *bool           `json:"valid,omitempty"`
	Whitelist          *WhitelistType  `json:"whitelist,omitempty"`
	Language           *string         `json:"language,omitempty" validate:"omitempty,len=2"`
	DefaultProfileType *ProfileType    `json:"default_profile_type,omitempty"`
	EnergyContract     *EnergyContract `json:"energy_contract,omitempty"`
	LastUpdated        time.Time       `json:"last_updated" validate:"required"`
}

// AuthorizationInfo: Contains information about the authorization, if the Token is allowed to charge and optionally which EVSEs are allowed to be used.
type AuthorizationInfo struct {
	Allowed                AllowedType         `json:"allowed" validate:"required"`
	Token                  Token               `json:"token" validate:"required"`
	Location               *LocationReferences `json:"location,omitempty"`
	AuthorizationReference *string             `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	Info                   *DisplayText        `json:"info,omitempty"`
}

// EnergyContract: Information about an energy contract that belongs to a Token so a driver could use his/her own energy contract when charging at a Charge Point.
type EnergyContract struct {
	SupplierName string  `json:"supplier_name" validate:"required,max=64"`
	ContractID   *string `json:"contract_id,omitempty" validate:"omitempty,max=64"`
}

// LocationReferences: References to location details.
type LocationReferences struct {
	LocationID string   `json:"location_id" validate:"required,max=36"`
	EVSEUids   []string `json:"evse_uids,omitempty"`
}

// AllowedType: Defines the allowed status of a Token.
type AllowedType string

const (
	AllowedTypeAllowed    AllowedType = "ALLOWED"
	AllowedTypeBlocked    AllowedType = "BLOCKED"
	AllowedTypeExpired    AllowedType = "EXPIRED"
	AllowedTypeNoCredit   AllowedType = "NO_CREDIT"
	AllowedTypeNotAllowed AllowedType = "NOT_ALLOWED"
)

// TokenType: The type of token.
type TokenType string

const (
	TokenTypeAdHocUser TokenType = "AD_HOC_USER"
	TokenTypeAppUser   TokenType = "APP_USER"
	TokenTypeOther     TokenType = "OTHER"
	TokenTypeRfid      TokenType = "RFID"
)

// WhitelistType: Defines when authorization of a Token by the CPO is allowed.
type WhitelistType string

const (
	WhitelistTypeAlways         WhitelistType = "ALWAYS"
	WhitelistTypeAllowed        WhitelistType = "ALLOWED"
	WhitelistTypeAllowedOffline WhitelistType = "ALLOWED_OFFLINE"
	WhitelistTypeNever          WhitelistType = "NEVER"
)
