openapi: 3.1.0
info:
  title: OCPI 2.2.1 - Tokens Module - Receiver Interface
  description: |
    The Receiver Interface (typically implemented by the CPO) allows the eMSP to push Token
    information to the CPO. Tokens are Client Owned Objects, so the endpoints contain the
    required extra fields: country_code, party_id and token_uid.
  version: 2.2.1
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.2.1 Specification
  url: https://github.com/ocpi/ocpi/blob/master/mod_tokens.asciidoc
security:
  - ocpiAuthorization: []
components:
  securitySchemes:
    ocpiAuthorization:
      $ref: "../../components/schema.yaml#/components/securitySchemes/ocpiAuthorization"

paths:
  /tokens/{country_code}/{party_id}/{token_uid}:
    get:
      operationId: receiverGetToken
      summary: Retrieve a Token
      tags: [ Tokens ]
      description: |
        If the eMSP wants to check the status of a Token in the CPO system it might GET the
        object from the CPO system for validation purposes. The eMSP is the owner of the objects,
        so it would be illogical if the CPO system had a different status or was missing an object.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenUidParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenTypeQueryParameter"
      responses:
        "200":
          description: Successful response containing the requested Token.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/Token"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"

    put:
      operationId: receiverPutToken
      summary: Create or update a Token
      tags: [ Tokens ]
      description: |
        New or updated Token objects are pushed from the eMSP to the CPO.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenUidParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenTypeQueryParameter"
      requestBody:
        description: New or updated Token object.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/Token"
      responses:
        "200":
          $ref: "../../components/schema.yaml#/components/responses/OCPISuccessResponse"
        "201":
          $ref: "../../components/schema.yaml#/components/responses/OCPICreatedResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

    patch:
      operationId: receiverPatchToken
      summary: Partially update a Token
      tags: [ Tokens ]
      description: |
        Same as the PUT method, but only the fields/objects that have to be updated have to be
        present, other fields/objects that are not specified are considered unchanged. Any request
        to the PATCH method SHALL contain the last_updated field.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenUidParameter"
        - $ref: "./parameters.yaml#/components/parameters/TokenTypeQueryParameter"
      requestBody:
        description: Partial Token object with only the fields to update.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/TokenPatch"
      responses:
        "200":
          $ref: "../../components/schema.yaml#/components/responses/OCPISuccessResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"
