// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// BookingsSenderClient calls the Bookings sender interface on a peer.
type BookingsSenderClient struct {
	c    *core.Client
	base string
}

// NewBookingsSenderClient binds a client to baseURL (the peer's bookings endpoint URL).
func NewBookingsSenderClient(c *core.Client, baseURL string) *BookingsSenderClient {
	return &BookingsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *BookingsSenderClient) GetBookingLocations(ctx context.Context, p core.PageOpts) (core.Page[BookingLocation], error) {
	u := x.base + "/" + "booking_locations"
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[BookingLocation]{}, err
	}
	out, err := core.Decode[[]BookingLocation](resp)
	if err != nil {
		return core.Page[BookingLocation]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[BookingLocation]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *BookingsSenderClient) GetBookingLocation(ctx context.Context, bookingLocationID string) (BookingLocation, error) {
	u := x.base + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero BookingLocation
		return zero, err
	}
	out, err := core.Decode[BookingLocation](resp)
	return out.Data, err
}

func (x *BookingsSenderClient) GetCalendar(ctx context.Context, bookingLocationID string, calendarID string) (Calendar, error) {
	u := x.base + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID) + "/" + url.PathEscape(calendarID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Calendar
		return zero, err
	}
	out, err := core.Decode[Calendar](resp)
	return out.Data, err
}

func (x *BookingsSenderClient) GetBookings(ctx context.Context, p core.PageOpts) (core.Page[Booking], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[Booking]{}, err
	}
	out, err := core.Decode[[]Booking](resp)
	if err != nil {
		return core.Page[Booking]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[Booking]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *BookingsSenderClient) PostBooking(ctx context.Context, body BookingRequest) (Booking, error) {
	u := x.base
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero Booking
		return zero, err
	}
	out, err := core.Decode[Booking](resp)
	return out.Data, err
}

// BookingsSenderHandler handles inbound Bookings sender requests.
type BookingsSenderHandler interface {
	GetBookingLocations(ctx context.Context, req core.PageReq) (core.Page[BookingLocation], *status.Error)
	GetBookingLocation(ctx context.Context, bookingLocationID string) (BookingLocation, *status.Error)
	GetCalendar(ctx context.Context, bookingLocationID string, calendarID string) (Calendar, *status.Error)
	GetBookings(ctx context.Context, req core.PageReq) (core.Page[Booking], *status.Error)
	PostBooking(ctx context.Context, body BookingRequest) (Booking, *status.Error)
}

// RegisterBookingsSender registers h's routes on mux under basePath (the module mount path).
func RegisterBookingsSender(mux *core.Mux, basePath string, h BookingsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/booking_locations", func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetBookingLocations(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/booking_locations/{booking_location_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetBookingLocation(r.Context(), r.PathValue("booking_location_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/booking_locations/{booking_location_id}/{calendar_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetCalendar(r.Context(), r.PathValue("booking_location_id"), r.PathValue("calendar_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetBookings(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodPost, base, func(w http.ResponseWriter, r *http.Request) {
		var body BookingRequest
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostBooking(r.Context(), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
