// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"github.com/shopspring/decimal"
	"time"
)

// Booking: A booking for a charge point or parking space at a location.
type Booking struct {
	ID                     string                 `json:"id" validate:"required,max=36"`
	CountryCode            string                 `json:"country_code" validate:"required,len=2"`
	PartyID                string                 `json:"party_id" validate:"required,len=3"`
	RequestID              string                 `json:"request_id" validate:"required,max=36"`
	BookingOption          *BookingOption         `json:"booking_option,omitempty"`
	LocationID             string                 `json:"location_id" validate:"required,max=36"`
	BookingTokens          []BookingToken         `json:"booking_tokens,omitempty"`
	TariffIds              []string               `json:"tariff_ids,omitempty"`
	Period                 Timeslot               `json:"period" validate:"required"`
	ReservationStatus      ReservationStatus      `json:"reservation_status" validate:"required"`
	Canceled               *Cancellation          `json:"canceled,omitempty"`
	AccessInformation      []AccessInformation    `json:"access_information,omitempty"`
	AuthorizationReference string                 `json:"authorization_reference" validate:"required,max=36"`
	BookingTerms           BookingTerms           `json:"booking_terms" validate:"required"`
	BookingRequests        []BookingRequestStatus `json:"booking_requests" validate:"required,min=1"`
	LastUpdated            time.Time              `json:"last_updated" validate:"required"`
}

// BookingLocation: A bookable location with availability calendars.
type BookingLocation struct {
	CountryCode   string         `json:"country_code" validate:"required,len=2"`
	PartyID       string         `json:"party_id" validate:"required,len=3"`
	ID            string         `json:"id" validate:"required,max=36"`
	LocationID    string         `json:"location_id" validate:"required,max=36"`
	BookingOption *BookingOption `json:"booking_option,omitempty"`
	Policy        *Policy        `json:"policy,omitempty"`
	TariffIds     []string       `json:"tariff_ids,omitempty"`
	BookingTerms  *BookingTerms  `json:"booking_terms,omitempty"`
	Calendars     []Calendar     `json:"calendars,omitempty"`
	LastUpdated   time.Time      `json:"last_updated" validate:"required"`
}

// Calendar: A calendar defining available booking timeslots.
type Calendar struct {
	ID                 string     `json:"id" validate:"required,max=36"`
	BeginFrom          time.Time  `json:"begin_from" validate:"required"`
	EndBefore          time.Time  `json:"end_before" validate:"required"`
	TimeslotIncrement  *int       `json:"timeslot_increment,omitempty"`
	AvailableTimeslots []Timeslot `json:"available_timeslots" validate:"required,min=1"`
	LastUpdated        time.Time  `json:"last_updated" validate:"required"`
}

// Timeslot: A time period with start and end, optionally with power and energy details.
type Timeslot struct {
	StartDateTime      time.Time        `json:"start_date_time" validate:"required"`
	EndDateTime        time.Time        `json:"end_date_time" validate:"required"`
	MinPower           *decimal.Decimal `json:"min_power,omitempty"`
	MaxPower           *decimal.Decimal `json:"max_power,omitempty"`
	GreenEnergySupport *bool            `json:"green_energy_support,omitempty"`
}

// Period: A period defined by start and end DateTime.
type Period struct {
	StartDateTime time.Time `json:"start_date_time" validate:"required"`
	EndDateTime   time.Time `json:"end_date_time" validate:"required"`
}

// BookingRequest: Request to create a new booking.
type BookingRequest struct {
	CountryCode            string              `json:"country_code" validate:"required,len=2"`
	PartyID                string              `json:"party_id" validate:"required,len=3"`
	RequestID              string              `json:"request_id" validate:"required,max=36"`
	BookingOption          *BookingOption      `json:"booking_option,omitempty"`
	LocationID             string              `json:"location_id" validate:"required,max=36"`
	BookingLocationID      string              `json:"booking_location_id" validate:"required,max=36"`
	Tokens                 []BookingToken      `json:"tokens,omitempty"`
	AccessInformation      []AccessInformation `json:"access_information,omitempty"`
	Period                 Period              `json:"period" validate:"required"`
	AuthorizationReference string              `json:"authorization_reference" validate:"required,max=36"`
	PowerRequired          *int                `json:"power_required,omitempty"`
	Canceled               *Cancellation       `json:"canceled,omitempty"`
}

// BookingRequestStatus: Status wrapper for a booking request.
type BookingRequestStatus struct {
	RequestStatus   ReservationRequestStatus `json:"request_status" validate:"required"`
	BookingRequest  BookingRequest           `json:"booking_request" validate:"required"`
	RequestReceived time.Time                `json:"request_received" validate:"required"`
}

// BookingOption: Specification of what can be booked at a location, describing EVSE, connector, and parking characteristics.
type BookingOption struct {
	EVSEUID               *string           `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	ConnectorID           *string           `json:"connector_id,omitempty" validate:"omitempty,max=36"`
	ParkingID             *string           `json:"parking_id,omitempty" validate:"omitempty,max=36"`
	EVSEPosition          []EVSEPosition    `json:"evse_position,omitempty"`
	VehicleTypes          []VehicleType     `json:"vehicle_types,omitempty"`
	ConnectorFormat       []ConnectorFormat `json:"connector_format,omitempty"`
	ConnectorTypes        []ConnectorType   `json:"connector_types,omitempty"`
	PowerTypes            []PowerType       `json:"power_types,omitempty"`
	MaxVehicleWeight      *decimal.Decimal  `json:"max_vehicle_weight,omitempty"`
	MaxVehicleHeight      *decimal.Decimal  `json:"max_vehicle_height,omitempty"`
	MaxVehicleLength      *decimal.Decimal  `json:"max_vehicle_length,omitempty"`
	MaxVehicleWidth       *decimal.Decimal  `json:"max_vehicle_width,omitempty"`
	MinParkingSpaceLength *decimal.Decimal  `json:"min_parking_space_length,omitempty"`
	MinParkingSpaceWidth  *decimal.Decimal  `json:"min_parking_space_width,omitempty"`
	DangerousGoodsAllowed *bool             `json:"dangerous_goods_allowed,omitempty"`
	DriveThrough          *bool             `json:"drive_through,omitempty"`
	RefrigerationOutlet   *bool             `json:"refrigeration_outlet,omitempty"`
}

// BookingToken: Token information for a booking, identifying the token that can be used.
type BookingToken struct {
	CountryCode string    `json:"country_code" validate:"required,len=2"`
	PartyID     string    `json:"party_id" validate:"required,len=3"`
	UID         string    `json:"uid" validate:"required,max=36"`
	Type        TokenType `json:"type" validate:"required"`
	ContractID  string    `json:"contract_id" validate:"required,max=36"`
}

// BookingTerms: Terms and conditions for the booking.
type BookingTerms struct {
	RfidAuthRequired           *bool            `json:"rfid_auth_required,omitempty"`
	TokenGroupsSupported       *bool            `json:"token_groups_supported,omitempty"`
	RemoteAuthSupported        *bool            `json:"remote_auth_supported,omitempty"`
	SupportedAccessMethods     []AccessMethod   `json:"supported_access_methods" validate:"required,min=1"`
	ChangeUntilMinutes         decimal.Decimal  `json:"change_until_minutes" validate:"required"`
	CancelUntilMinutes         decimal.Decimal  `json:"cancel_until_minutes" validate:"required"`
	ChangeNotAllowed           *bool            `json:"change_not_allowed,omitempty"`
	EarlyStartAllowed          *bool            `json:"early_start_allowed,omitempty"`
	EarlyStartTime             *decimal.Decimal `json:"early_start_time,omitempty"`
	NoshowTimeout              *decimal.Decimal `json:"noshow_timeout,omitempty"`
	NoshowFee                  *bool            `json:"noshow_fee,omitempty"`
	LateStopAllowed            *bool            `json:"late_stop_allowed,omitempty"`
	LateStopTime               *decimal.Decimal `json:"late_stop_time,omitempty"`
	OverlappingBookingsAllowed *bool            `json:"overlapping_bookings_allowed,omitempty"`
	MinBookingDuration         *decimal.Decimal `json:"min_booking_duration,omitempty"`
	MaxBookingDuration         *decimal.Decimal `json:"max_booking_duration,omitempty"`
	BookingTerms               *string          `json:"booking_terms,omitempty"`
}

// AccessInformation: Information on how to access the booked resource.
type AccessInformation struct {
	Method AccessMethod `json:"method" validate:"required"`
	Value  *string      `json:"value,omitempty"`
}

// AccessMethod: Method to access the booked resource.
type AccessMethod string

const (
	AccessMethodOpen          AccessMethod = "OPEN"
	AccessMethodToken         AccessMethod = "TOKEN"
	AccessMethodLicensePlate  AccessMethod = "LICENSE_PLATE"
	AccessMethodAccessCode    AccessMethod = "ACCESS_CODE"
	AccessMethodIntercom      AccessMethod = "INTERCOM"
	AccessMethodParkingTicket AccessMethod = "PARKING_TICKET"
)

// Cancellation: Cancellation details.
type Cancellation struct {
	CancellationReason CanceledReason `json:"cancellation_reason" validate:"required"`
	WhoCanceled        Role           `json:"who_canceled" validate:"required"`
}

// CanceledReason: Reason for cancellation.
type CanceledReason string

const (
	CanceledReasonPowerOutage   CanceledReason = "POWER_OUTAGE"
	CanceledReasonBrokenCharger CanceledReason = "BROKEN_CHARGER"
	CanceledReasonFull          CanceledReason = "FULL"
	CanceledReasonBlocked       CanceledReason = "BLOCKED"
	CanceledReasonTraffic       CanceledReason = "TRAFFIC"
	CanceledReasonBrokenVehicle CanceledReason = "BROKEN_VEHICLE"
	CanceledReasonNoCanceled    CanceledReason = "NO_CANCELED"
	CanceledReasonUnknown       CanceledReason = "UNKNOWN"
)

// Policy: Booking policy for a location.
type Policy struct {
	ReservationRequired bool             `json:"reservation_required"`
	AdHoc               *decimal.Decimal `json:"ad_hoc,omitempty"`
}

// ReservationStatus: Status of the reservation/booking.
type ReservationStatus string

const (
	ReservationStatusPending   ReservationStatus = "PENDING"
	ReservationStatusReserved  ReservationStatus = "RESERVED"
	ReservationStatusCanceled  ReservationStatus = "CANCELED"
	ReservationStatusFailed    ReservationStatus = "FAILED"
	ReservationStatusNoShow    ReservationStatus = "NO_SHOW"
	ReservationStatusFulfilled ReservationStatus = "FULFILLED"
	ReservationStatusRejected  ReservationStatus = "REJECTED"
	ReservationStatusUnknown   ReservationStatus = "UNKNOWN"
)

// ReservationRequestStatus: Status of a booking request.
type ReservationRequestStatus string

const (
	ReservationRequestStatusPending  ReservationRequestStatus = "PENDING"
	ReservationRequestStatusAccepted ReservationRequestStatus = "ACCEPTED"
	ReservationRequestStatusDeclined ReservationRequestStatus = "DECLINED"
	ReservationRequestStatusFailed   ReservationRequestStatus = "FAILED"
)

// BookingLocationPatch: Partial BookingLocation for PATCH requests. Only fields present will be updated. last_updated is required.
type BookingLocationPatch struct {
	BookingOption *BookingOption `json:"booking_option,omitempty"`
	Policy        *Policy        `json:"policy,omitempty"`
	TariffIds     []string       `json:"tariff_ids,omitempty"`
	BookingTerms  *BookingTerms  `json:"booking_terms,omitempty"`
	Calendars     []Calendar     `json:"calendars,omitempty"`
	LastUpdated   time.Time      `json:"last_updated" validate:"required"`
}

// BookingPatch: Partial Booking for PATCH requests. Only fields present will be updated. last_updated is required.
type BookingPatch struct {
	BookingOption          *BookingOption         `json:"booking_option,omitempty"`
	LocationID             *string                `json:"location_id,omitempty" validate:"omitempty,max=36"`
	BookingTokens          []BookingToken         `json:"booking_tokens,omitempty"`
	TariffIds              []string               `json:"tariff_ids,omitempty"`
	Period                 *Timeslot              `json:"period,omitempty"`
	ReservationStatus      *ReservationStatus     `json:"reservation_status,omitempty"`
	Canceled               *Cancellation          `json:"canceled,omitempty"`
	AccessInformation      []AccessInformation    `json:"access_information,omitempty"`
	AuthorizationReference *string                `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	BookingTerms           *BookingTerms          `json:"booking_terms,omitempty"`
	BookingRequests        []BookingRequestStatus `json:"booking_requests,omitempty"`
	LastUpdated            time.Time              `json:"last_updated" validate:"required"`
}

// CalendarPatch: Partial Calendar for PATCH requests. Only fields present will be updated. last_updated is required.
type CalendarPatch struct {
	BeginFrom          *time.Time `json:"begin_from,omitempty"`
	EndBefore          *time.Time `json:"end_before,omitempty"`
	TimeslotIncrement  *int       `json:"timeslot_increment,omitempty"`
	AvailableTimeslots []Timeslot `json:"available_timeslots,omitempty"`
	LastUpdated        time.Time  `json:"last_updated" validate:"required"`
}
