// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// BookingsReceiverClient calls the Bookings receiver interface on a peer.
type BookingsReceiverClient struct {
	c    *core.Client
	base string
}

// NewBookingsReceiverClient binds a client to baseURL (the peer's bookings endpoint URL).
func NewBookingsReceiverClient(c *core.Client, baseURL string) *BookingsReceiverClient {
	return &BookingsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *BookingsReceiverClient) GetBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string) (BookingLocation, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero BookingLocation
		return zero, err
	}
	out, err := core.Decode[BookingLocation](resp)
	return out.Data, err
}

func (x *BookingsReceiverClient) PutBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string, body BookingLocation) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *BookingsReceiverClient) PatchBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string, body BookingLocationPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *BookingsReceiverClient) GetCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string) (Calendar, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID) + "/" + url.PathEscape(calendarID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Calendar
		return zero, err
	}
	out, err := core.Decode[Calendar](resp)
	return out.Data, err
}

func (x *BookingsReceiverClient) PutCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string, body Calendar) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID) + "/" + url.PathEscape(calendarID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *BookingsReceiverClient) PatchCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string, body CalendarPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + "booking_locations" + "/" + url.PathEscape(bookingLocationID) + "/" + url.PathEscape(calendarID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *BookingsReceiverClient) GetBooking(ctx context.Context, countryCode string, partyID string, bookingID string) (Booking, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(bookingID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Booking
		return zero, err
	}
	out, err := core.Decode[Booking](resp)
	return out.Data, err
}

func (x *BookingsReceiverClient) PutBooking(ctx context.Context, countryCode string, partyID string, bookingID string, body Booking) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(bookingID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *BookingsReceiverClient) PatchBooking(ctx context.Context, countryCode string, partyID string, bookingID string, body BookingPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(bookingID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// BookingsReceiverHandler handles inbound Bookings receiver requests.
type BookingsReceiverHandler interface {
	GetBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string) (BookingLocation, *status.Error)
	PutBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string, body BookingLocation) *status.Error
	PatchBookingLocation(ctx context.Context, countryCode string, partyID string, bookingLocationID string, body BookingLocationPatch) *status.Error
	GetCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string) (Calendar, *status.Error)
	PutCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string, body Calendar) *status.Error
	PatchCalendar(ctx context.Context, countryCode string, partyID string, bookingLocationID string, calendarID string, body CalendarPatch) *status.Error
	GetBooking(ctx context.Context, countryCode string, partyID string, bookingID string) (Booking, *status.Error)
	PutBooking(ctx context.Context, countryCode string, partyID string, bookingID string, body Booking) *status.Error
	PatchBooking(ctx context.Context, countryCode string, partyID string, bookingID string, body BookingPatch) *status.Error
}

// RegisterBookingsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterBookingsReceiver(mux *core.Mux, basePath string, h BookingsReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetBookingLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}", func(w http.ResponseWriter, r *http.Request) {
		var body BookingLocation
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutBookingLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}", func(w http.ResponseWriter, r *http.Request) {
		var body BookingLocationPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchBookingLocation(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}/{calendar_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetCalendar(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"), r.PathValue("calendar_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}/{calendar_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Calendar
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutCalendar(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"), r.PathValue("calendar_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/booking_locations/{booking_location_id}/{calendar_id}", func(w http.ResponseWriter, r *http.Request) {
		var body CalendarPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchCalendar(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_location_id"), r.PathValue("calendar_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{booking_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetBooking(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{booking_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Booking
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutBooking(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{booking_id}", func(w http.ResponseWriter, r *http.Request) {
		var body BookingPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchBooking(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("booking_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
