// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// CdrsReceiverClient calls the Cdrs receiver interface on a peer.
type CdrsReceiverClient struct {
	c    *core.Client
	base string
}

// NewCdrsReceiverClient binds a client to baseURL (the peer's cdrs endpoint URL).
func NewCdrsReceiverClient(c *core.Client, baseURL string) *CdrsReceiverClient {
	return &CdrsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *CdrsReceiverClient) PostCdr(ctx context.Context, body CDR) error {
	u := x.base
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *CdrsReceiverClient) GetCdr(ctx context.Context, cDRID string) (CDR, error) {
	u := x.base + "/" + url.PathEscape(cDRID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero CDR
		return zero, err
	}
	out, err := core.Decode[CDR](resp)
	return out.Data, err
}

// CdrsReceiverHandler handles inbound Cdrs receiver requests.
type CdrsReceiverHandler interface {
	PostCdr(ctx context.Context, body CDR) *status.Error
	GetCdr(ctx context.Context, cDRID string) (CDR, *status.Error)
}

// RegisterCdrsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterCdrsReceiver(mux *core.Mux, basePath string, h CdrsReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodPost, base, func(w http.ResponseWriter, r *http.Request) {
		var body CDR
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PostCdr(r.Context(), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/{cdr_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetCdr(r.Context(), r.PathValue("cdr_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
