// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// ChargingprofilesReceiverClient calls the Chargingprofiles receiver interface on a peer.
type ChargingprofilesReceiverClient struct {
	c    *core.Client
	base string
}

// NewChargingprofilesReceiverClient binds a client to baseURL (the peer's chargingprofiles endpoint URL).
func NewChargingprofilesReceiverClient(c *core.Client, baseURL string) *ChargingprofilesReceiverClient {
	return &ChargingprofilesReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *ChargingprofilesReceiverClient) GetActiveChargingProfile(ctx context.Context, sessionID string) (ChargingProfileResponse, error) {
	u := x.base + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero ChargingProfileResponse
		return zero, err
	}
	out, err := core.Decode[ChargingProfileResponse](resp)
	return out.Data, err
}

func (x *ChargingprofilesReceiverClient) PutChargingProfile(ctx context.Context, sessionID string, body SetChargingProfile) (ChargingProfileResponse, error) {
	u := x.base + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		var zero ChargingProfileResponse
		return zero, err
	}
	out, err := core.Decode[ChargingProfileResponse](resp)
	return out.Data, err
}

func (x *ChargingprofilesReceiverClient) DeleteChargingProfile(ctx context.Context, sessionID string) (ChargingProfileResponse, error) {
	u := x.base + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodDelete, u, nil)
	if err != nil {
		var zero ChargingProfileResponse
		return zero, err
	}
	out, err := core.Decode[ChargingProfileResponse](resp)
	return out.Data, err
}

// ChargingprofilesReceiverHandler handles inbound Chargingprofiles receiver requests.
type ChargingprofilesReceiverHandler interface {
	GetActiveChargingProfile(ctx context.Context, sessionID string) (ChargingProfileResponse, *status.Error)
	PutChargingProfile(ctx context.Context, sessionID string, body SetChargingProfile) (ChargingProfileResponse, *status.Error)
	DeleteChargingProfile(ctx context.Context, sessionID string) (ChargingProfileResponse, *status.Error)
}

// RegisterChargingprofilesReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterChargingprofilesReceiver(mux *core.Mux, basePath string, h ChargingprofilesReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetActiveChargingProfile(r.Context(), r.PathValue("session_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		var body SetChargingProfile
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PutChargingProfile(r.Context(), r.PathValue("session_id"), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodDelete, base+"/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.DeleteChargingProfile(r.Context(), r.PathValue("session_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
