// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// CommandsSenderClient calls the Commands sender interface on a peer.
type CommandsSenderClient struct {
	c    *core.Client
	base string
}

// NewCommandsSenderClient binds a client to baseURL (the peer's commands endpoint URL).
func NewCommandsSenderClient(c *core.Client, baseURL string) *CommandsSenderClient {
	return &CommandsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *CommandsSenderClient) PostCommandResult(ctx context.Context, body CommandResult) error {
	u := x.base
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// CommandsSenderHandler handles inbound Commands sender requests.
type CommandsSenderHandler interface {
	PostCommandResult(ctx context.Context, body CommandResult) *status.Error
}

// RegisterCommandsSender registers h's routes on mux under basePath (the module mount path).
func RegisterCommandsSender(mux *core.Mux, basePath string, h CommandsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodPost, base, func(w http.ResponseWriter, r *http.Request) {
		var body CommandResult
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PostCommandResult(r.Context(), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
