// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"time"
)

// CancelReservation: With CancelReservation the Sender can request the Cancel of an existing Reservation.
// The CancelReservation needs to contain the reservation_id that was given by the Sender to the ReserveNow.
// As there might be cost involved for a Reservation, canceling a reservation might still result in a CDR being sent for the reservation.
type CancelReservation struct {
	ResponseURL   string `json:"response_url" validate:"required"`
	ReservationID string `json:"reservation_id" validate:"required,max=36"`
}

// ReserveNow: The evse_uid is optional. If no EVSE is specified, the Charge Point should keep one EVSE available
// for the EV Driver identified by the given Token. (This might not be supported by all Charge Points).
// A reservation can be replaced/updated by sending a RESERVE_NOW request with the same Location
// (Charge Point) and the same reservation_id.
type ReserveNow struct {
	ResponseURL            string    `json:"response_url" validate:"required"`
	Token                  Token     `json:"token" validate:"required"`
	ExpiryDate             time.Time `json:"expiry_date" validate:"required"`
	ReservationID          string    `json:"reservation_id" validate:"required,max=36"`
	LocationID             string    `json:"location_id" validate:"required,max=36"`
	EVSEUID                *string   `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	AuthorizationReference *string   `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
}

// StartSession: The evse_uid is optional. If no EVSE is specified, the Charge Point can itself decide on which EVSE
// to start a new session. (This might not be supported by all Charge Points).
// The eMSP provides a Token that has to be used by the Charge Point.
type StartSession struct {
	ResponseURL            string  `json:"response_url" validate:"required"`
	Token                  Token   `json:"token" validate:"required"`
	LocationID             string  `json:"location_id" validate:"required,max=36"`
	EVSEUID                *string `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	ConnectorID            *string `json:"connector_id,omitempty" validate:"omitempty,max=36"`
	AuthorizationReference *string `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
}

// StopSession: Object to stop an ongoing session.
type StopSession struct {
	ResponseURL string `json:"response_url" validate:"required"`
	SessionID   string `json:"session_id" validate:"required,max=36"`
}

// UnlockConnector: Object to request unlock of a connector. Use with care!
// The command UNLOCK_CONNECTOR may only be used by an operator or the eMSP.
// This command SHALL never be allowed to be sent directly by the EV-Driver.
type UnlockConnector struct {
	ResponseURL string `json:"response_url" validate:"required"`
	LocationID  string `json:"location_id" validate:"required,max=36"`
	EVSEUID     string `json:"evse_uid" validate:"required,max=36"`
	ConnectorID string `json:"connector_id" validate:"required,max=36"`
}

// CommandResponse: The CommandResponse object is sent in the HTTP response body.
// It contains the direct response from the CPO, not the response from the Charge Point.
type CommandResponse struct {
	Result  CommandResponseType `json:"result" validate:"required"`
	Timeout int                 `json:"timeout" validate:"required"`
	Message []DisplayText       `json:"message,omitempty"`
}

// CommandResult: Result of the command request as sent by the Charge Point to the CPO,
// forwarded to the eMSP.
type CommandResult struct {
	Result  CommandResultType `json:"result" validate:"required"`
	Message []DisplayText     `json:"message,omitempty"`
}

// CommandResponseType: Response to the command request from the eMSP to the CPO.
type CommandResponseType string

const (
	CommandResponseTypeNotSupported   CommandResponseType = "NOT_SUPPORTED"
	CommandResponseTypeRejected       CommandResponseType = "REJECTED"
	CommandResponseTypeAccepted       CommandResponseType = "ACCEPTED"
	CommandResponseTypeUnknownSession CommandResponseType = "UNKNOWN_SESSION"
)

// CommandResultType: Result of the command that was sent to the Charge Point.
type CommandResultType string

const (
	CommandResultTypeAccepted            CommandResultType = "ACCEPTED"
	CommandResultTypeCanceledReservation CommandResultType = "CANCELED_RESERVATION"
	CommandResultTypeEvseOccupied        CommandResultType = "EVSE_OCCUPIED"
	CommandResultTypeEvseInoperative     CommandResultType = "EVSE_INOPERATIVE"
	CommandResultTypeFailed              CommandResultType = "FAILED"
	CommandResultTypeNotSupported        CommandResultType = "NOT_SUPPORTED"
	CommandResultTypeRejected            CommandResultType = "REJECTED"
	CommandResultTypeTimeout             CommandResultType = "TIMEOUT"
	CommandResultTypeUnknownReservation  CommandResultType = "UNKNOWN_RESERVATION"
)

// CommandType: The command requested.
type CommandType string

const (
	CommandTypeCancelReservation CommandType = "CANCEL_RESERVATION"
	CommandTypeReserveNow        CommandType = "RESERVE_NOW"
	CommandTypeStartSession      CommandType = "START_SESSION"
	CommandTypeStopSession       CommandType = "STOP_SESSION"
	CommandTypeUnlockConnector   CommandType = "UNLOCK_CONNECTOR"
)
