// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"github.com/shopspring/decimal"
)

// BusinessDetails: Business details of an operator, suboperator, or owner.
type BusinessDetails struct {
	Name    string  `json:"name" validate:"required,max=100"`
	Website *string `json:"website,omitempty"`
	Logo    *Image  `json:"logo,omitempty"`
}

// DisplayText: Multi-language text with a language code and text value.
type DisplayText struct {
	Language string `json:"language" validate:"required,len=2"`
	Text     string `json:"text" validate:"required,max=512"`
}

// Image: This class references an image related to an EVSE in terms of a file name or url.
// Per charge point an unlimited number of images of each type is allowed.
// Recommended are at least two images where one is a network or provider logo and the second is a station photo.
type Image struct {
	URL       string        `json:"url" validate:"required"`
	Thumbnail *string       `json:"thumbnail,omitempty"`
	Category  ImageCategory `json:"category" validate:"required"`
	Type      string        `json:"type" validate:"required,max=4"`
	Width     *int          `json:"width,omitempty"`
	Height    *int          `json:"height,omitempty"`
}

// ImageCategory: The category of an image to obtain the correct usage in a user presentation. The category has to be set accordingly to the image content in order to guarantee the right usage.
type ImageCategory string

const (
	ImageCategoryCharger  ImageCategory = "CHARGER"
	ImageCategoryEntrance ImageCategory = "ENTRANCE"
	ImageCategoryLocation ImageCategory = "LOCATION"
	ImageCategoryNetwork  ImageCategory = "NETWORK"
	ImageCategoryOperator ImageCategory = "OPERATOR"
	ImageCategoryOther    ImageCategory = "OTHER"
	ImageCategoryOwner    ImageCategory = "OWNER"
)

// Price: Price information with tax details.
type Price struct {
	BeforeTaxes decimal.Decimal `json:"before_taxes" validate:"required"`
	Taxes       []TaxAmount     `json:"taxes,omitempty"`
}

// TaxAmount: Tax information for a price component.
type TaxAmount struct {
	Name          string           `json:"name" validate:"required"`
	AccountNumber *string          `json:"account_number,omitempty"`
	Percentage    *decimal.Decimal `json:"percentage,omitempty"`
	Amount        decimal.Decimal  `json:"amount" validate:"required"`
}
