// Code generated by gocpi codegen. DO NOT EDIT.

package v230

// Credentials: The Credentials object describes the credentials and related information to access
// a party's platform. Every role needs a unique combination of: role, party_id and country_code.
type Credentials struct {
	Token      string            `json:"token" validate:"required,max=64"`
	URL        string            `json:"url" validate:"required"`
	HubPartyID *string           `json:"hub_party_id,omitempty" validate:"omitempty,len=5"`
	Roles      []CredentialsRole `json:"roles" validate:"required,min=1"`
}

// CredentialsRole: Role information for a credentials exchange.
type CredentialsRole struct {
	Role            Role            `json:"role" validate:"required"`
	BusinessDetails BusinessDetails `json:"business_details" validate:"required"`
	PartyID         string          `json:"party_id" validate:"required,len=3"`
	CountryCode     string          `json:"country_code" validate:"required,len=2"`
}
