// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"time"
)

// ClientInfo: Contains info about a connected party.
type ClientInfo struct {
	PartyID     string           `json:"party_id" validate:"required,len=3"`
	CountryCode string           `json:"country_code" validate:"required,len=2"`
	Role        Role             `json:"role" validate:"required"`
	Status      ConnectionStatus `json:"status" validate:"required"`
	LastUpdated time.Time        `json:"last_updated" validate:"required"`
}

// ConnectionStatus: Status of the connection to a party.
type ConnectionStatus string

const (
	ConnectionStatusConnected ConnectionStatus = "CONNECTED"
	ConnectionStatusOffline   ConnectionStatus = "OFFLINE"
	ConnectionStatusPlanned   ConnectionStatus = "PLANNED"
	ConnectionStatusSuspended ConnectionStatus = "SUSPENDED"
)

// Role: The role of a party in the OCPI ecosystem.
type Role string

const (
	RoleCpo   Role = "CPO"
	RoleEmsp  Role = "EMSP"
	RoleNap   Role = "NAP"
	RoleNsp   Role = "NSP"
	RoleOther Role = "OTHER"
	RoleScsp  Role = "SCSP"
)
