// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// PaymentsReceiverClient calls the Payments receiver interface on a peer.
type PaymentsReceiverClient struct {
	c    *core.Client
	base string
}

// NewPaymentsReceiverClient binds a client to baseURL (the peer's payments endpoint URL).
func NewPaymentsReceiverClient(c *core.Client, baseURL string) *PaymentsReceiverClient {
	return &PaymentsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *PaymentsReceiverClient) GetTerminal(ctx context.Context, terminalID string) (Terminal, error) {
	u := x.base + "/" + "terminals" + "/" + url.PathEscape(terminalID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Terminal
		return zero, err
	}
	out, err := core.Decode[Terminal](resp)
	return out.Data, err
}

func (x *PaymentsReceiverClient) PostTerminal(ctx context.Context, body Terminal) error {
	u := x.base + "/" + "terminals"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *PaymentsReceiverClient) GetFinancialAdviceConfirmation(ctx context.Context, financialAdviceConfirmationID string) (FinancialAdviceConfirmation, error) {
	u := x.base + "/" + "financial-advice-confirmations" + "/" + url.PathEscape(financialAdviceConfirmationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero FinancialAdviceConfirmation
		return zero, err
	}
	out, err := core.Decode[FinancialAdviceConfirmation](resp)
	return out.Data, err
}

func (x *PaymentsReceiverClient) PostFinancialAdviceConfirmation(ctx context.Context, body FinancialAdviceConfirmation) error {
	u := x.base + "/" + "financial-advice-confirmations"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// PaymentsReceiverHandler handles inbound Payments receiver requests.
type PaymentsReceiverHandler interface {
	GetTerminal(ctx context.Context, terminalID string) (Terminal, *status.Error)
	PostTerminal(ctx context.Context, body Terminal) *status.Error
	GetFinancialAdviceConfirmation(ctx context.Context, financialAdviceConfirmationID string) (FinancialAdviceConfirmation, *status.Error)
	PostFinancialAdviceConfirmation(ctx context.Context, body FinancialAdviceConfirmation) *status.Error
}

// RegisterPaymentsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterPaymentsReceiver(mux *core.Mux, basePath string, h PaymentsReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/terminals/{terminal_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetTerminal(r.Context(), r.PathValue("terminal_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/terminals", func(w http.ResponseWriter, r *http.Request) {
		var body Terminal
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PostTerminal(r.Context(), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/financial-advice-confirmations/{financial_advice_confirmation_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetFinancialAdviceConfirmation(r.Context(), r.PathValue("financial_advice_confirmation_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/financial-advice-confirmations", func(w http.ResponseWriter, r *http.Request) {
		var body FinancialAdviceConfirmation
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PostFinancialAdviceConfirmation(r.Context(), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
