// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"time"
)

// Terminal: A Terminal object describes a payment terminal at or near a charging location.
// The PTP (Payment Terminal Provider) manages these terminals and shares information
// with the CPO.
type Terminal struct {
	TerminalID        string          `json:"terminal_id" validate:"required,max=36"`
	CustomerReference *string         `json:"customer_reference,omitempty" validate:"omitempty,max=36"`
	PartyID           *string         `json:"party_id,omitempty" validate:"omitempty,len=3"`
	CountryCode       *string         `json:"country_code,omitempty" validate:"omitempty,len=2"`
	Address           *string         `json:"address,omitempty" validate:"omitempty,max=45"`
	City              *string         `json:"city,omitempty" validate:"omitempty,max=45"`
	PostalCode        *string         `json:"postal_code,omitempty" validate:"omitempty,max=10"`
	State             *string         `json:"state,omitempty" validate:"omitempty,max=20"`
	Country           *string         `json:"country,omitempty" validate:"omitempty,len=3"`
	Coordinates       *GeoLocation    `json:"coordinates,omitempty"`
	InvoiceBaseURL    *string         `json:"invoice_base_url,omitempty"`
	InvoiceCreator    *InvoiceCreator `json:"invoice_creator,omitempty"`
	Reference         *string         `json:"reference,omitempty" validate:"omitempty,max=36"`
	LocationIds       []string        `json:"location_ids,omitempty"`
	EVSEUids          []string        `json:"evse_uids,omitempty"`
	LastUpdated       time.Time       `json:"last_updated" validate:"required"`
}

// TerminalPatch: Partial Terminal object for PATCH requests. Only fields present will be updated.
type TerminalPatch struct {
	LocationIds []string `json:"location_ids,omitempty"`
	EVSEUids    []string `json:"evse_uids,omitempty"`
}

// FinancialAdviceConfirmation: A FinancialAdviceConfirmation contains the result of a financial advice
// (pre-authorization or capture) for a charging session payment.
type FinancialAdviceConfirmation struct {
	ID                     string            `json:"id" validate:"required,max=36"`
	AuthorizationReference string            `json:"authorization_reference" validate:"required,max=36"`
	TotalCosts             Price             `json:"total_costs" validate:"required"`
	Currency               string            `json:"currency" validate:"required,len=3"`
	EftData                []string          `json:"eft_data" validate:"required,min=1"`
	CaptureStatusCode      CaptureStatusCode `json:"capture_status_code" validate:"required"`
	CaptureStatusMessage   *string           `json:"capture_status_message,omitempty" validate:"omitempty,max=255"`
	LastUpdated            time.Time         `json:"last_updated" validate:"required"`
}

// TerminalActivation: Terminal object used for the activation request. The terminal_id is optional in the
// activation request as it will be set by the PTP.
type TerminalActivation struct {
	TerminalID        *string         `json:"terminal_id,omitempty" validate:"omitempty,max=36"`
	CustomerReference *string         `json:"customer_reference,omitempty" validate:"omitempty,max=36"`
	PartyID           *string         `json:"party_id,omitempty" validate:"omitempty,max=3"`
	CountryCode       *string         `json:"country_code,omitempty" validate:"omitempty,max=2"`
	Address           *string         `json:"address,omitempty" validate:"omitempty,max=45"`
	City              *string         `json:"city,omitempty" validate:"omitempty,max=45"`
	PostalCode        *string         `json:"postal_code,omitempty" validate:"omitempty,max=10"`
	State             *string         `json:"state,omitempty" validate:"omitempty,max=20"`
	Country           *string         `json:"country,omitempty" validate:"omitempty,max=3"`
	Coordinates       *GeoLocation    `json:"coordinates,omitempty"`
	InvoiceBaseURL    *string         `json:"invoice_base_url,omitempty"`
	InvoiceCreator    *InvoiceCreator `json:"invoice_creator,omitempty"`
	Reference         *string         `json:"reference,omitempty" validate:"omitempty,max=36"`
	LocationIds       []string        `json:"location_ids,omitempty"`
	EVSEUids          []string        `json:"evse_uids,omitempty"`
	LastUpdated       time.Time       `json:"last_updated" validate:"required"`
}

// InvoiceCreator: Defines who creates the invoice for the charging session.
type InvoiceCreator string

const (
	InvoiceCreatorCpo InvoiceCreator = "CPO"
	InvoiceCreatorPtp InvoiceCreator = "PTP"
)

// CaptureStatusCode: This enumeration describes the status of the payment capture process following a transaction at an EV charging station. It helps determine the outcome of the transaction and facilitates accurate financial reporting and customer billing.
type CaptureStatusCode string

const (
	CaptureStatusCodeSuccess        CaptureStatusCode = "SUCCESS"
	CaptureStatusCodePartialSuccess CaptureStatusCode = "PARTIAL_SUCCESS"
	CaptureStatusCodeFailed         CaptureStatusCode = "FAILED"
)
