// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// PaymentsSenderClient calls the Payments sender interface on a peer.
type PaymentsSenderClient struct {
	c    *core.Client
	base string
}

// NewPaymentsSenderClient binds a client to baseURL (the peer's payments endpoint URL).
func NewPaymentsSenderClient(c *core.Client, baseURL string) *PaymentsSenderClient {
	return &PaymentsSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *PaymentsSenderClient) GetTerminals(ctx context.Context, p core.PageOpts) (core.Page[Terminal], error) {
	u := x.base + "/" + "terminals"
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[Terminal]{}, err
	}
	out, err := core.Decode[[]Terminal](resp)
	if err != nil {
		return core.Page[Terminal]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[Terminal]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *PaymentsSenderClient) GetTerminal(ctx context.Context, terminalID string) (Terminal, error) {
	u := x.base + "/" + "terminals" + "/" + url.PathEscape(terminalID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Terminal
		return zero, err
	}
	out, err := core.Decode[Terminal](resp)
	return out.Data, err
}

func (x *PaymentsSenderClient) PutTerminal(ctx context.Context, terminalID string, body Terminal) error {
	u := x.base + "/" + "terminals" + "/" + url.PathEscape(terminalID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *PaymentsSenderClient) PatchTerminal(ctx context.Context, terminalID string, body TerminalPatch) error {
	u := x.base + "/" + "terminals" + "/" + url.PathEscape(terminalID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *PaymentsSenderClient) PostActivateTerminal(ctx context.Context, body TerminalActivation) error {
	u := x.base + "/" + "terminals" + "/" + "activate"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *PaymentsSenderClient) PostDeactivateTerminal(ctx context.Context, terminalID string) error {
	u := x.base + "/" + "terminals" + "/" + url.PathEscape(terminalID) + "/" + "deactivate"
	resp, err := x.c.Do(ctx, http.MethodPost, u, nil)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *PaymentsSenderClient) GetFinancialAdviceConfirmations(ctx context.Context, p core.PageOpts) (core.Page[FinancialAdviceConfirmation], error) {
	u := x.base + "/" + "financial-advice-confirmations"
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[FinancialAdviceConfirmation]{}, err
	}
	out, err := core.Decode[[]FinancialAdviceConfirmation](resp)
	if err != nil {
		return core.Page[FinancialAdviceConfirmation]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[FinancialAdviceConfirmation]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *PaymentsSenderClient) GetFinancialAdviceConfirmation(ctx context.Context, financialAdviceConfirmationID string) (FinancialAdviceConfirmation, error) {
	u := x.base + "/" + "financial-advice-confirmations" + "/" + url.PathEscape(financialAdviceConfirmationID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero FinancialAdviceConfirmation
		return zero, err
	}
	out, err := core.Decode[FinancialAdviceConfirmation](resp)
	return out.Data, err
}

// PaymentsSenderHandler handles inbound Payments sender requests.
type PaymentsSenderHandler interface {
	GetTerminals(ctx context.Context, req core.PageReq) (core.Page[Terminal], *status.Error)
	GetTerminal(ctx context.Context, terminalID string) (Terminal, *status.Error)
	PutTerminal(ctx context.Context, terminalID string, body Terminal) *status.Error
	PatchTerminal(ctx context.Context, terminalID string, body TerminalPatch) *status.Error
	PostActivateTerminal(ctx context.Context, body TerminalActivation) *status.Error
	PostDeactivateTerminal(ctx context.Context, terminalID string) *status.Error
	GetFinancialAdviceConfirmations(ctx context.Context, req core.PageReq) (core.Page[FinancialAdviceConfirmation], *status.Error)
	GetFinancialAdviceConfirmation(ctx context.Context, financialAdviceConfirmationID string) (FinancialAdviceConfirmation, *status.Error)
}

// RegisterPaymentsSender registers h's routes on mux under basePath (the module mount path).
func RegisterPaymentsSender(mux *core.Mux, basePath string, h PaymentsSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/terminals", func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetTerminals(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/terminals/{terminal_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetTerminal(r.Context(), r.PathValue("terminal_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/terminals/{terminal_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Terminal
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutTerminal(r.Context(), r.PathValue("terminal_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/terminals/{terminal_id}", func(w http.ResponseWriter, r *http.Request) {
		var body TerminalPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchTerminal(r.Context(), r.PathValue("terminal_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/terminals/activate", func(w http.ResponseWriter, r *http.Request) {
		var body TerminalActivation
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PostActivateTerminal(r.Context(), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/terminals/{terminal_id}/deactivate", func(w http.ResponseWriter, r *http.Request) {
		if herr := h.PostDeactivateTerminal(r.Context(), r.PathValue("terminal_id")); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/financial-advice-confirmations", func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetFinancialAdviceConfirmations(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodGet, base+"/financial-advice-confirmations/{financial_advice_confirmation_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetFinancialAdviceConfirmation(r.Context(), r.PathValue("financial_advice_confirmation_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
