// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import "github.com/shiv3/gocpi/core"

// CPOHandlers groups the functional-module handlers a CPO platform provides.
// A nil field skips registering that module.
type CPOHandlers struct {
	Locations        LocationsSenderHandler
	Sessions         SessionsSenderHandler
	Cdrs             CdrsSenderHandler
	Tariffs          TariffsSenderHandler
	Tokens           TokensReceiverHandler
	Commands         CommandsReceiverHandler
	Chargingprofiles ChargingprofilesReceiverHandler
}

// RegisterCPO mounts the CPO functional-module endpoints under baseURL;
// each module is mounted at baseURL + "/<module>".
func RegisterCPO(mux *core.Mux, baseURL string, h CPOHandlers) {
	if h.Locations != nil {
		RegisterLocationsSender(mux, baseURL+"/locations", h.Locations)
	}
	if h.Sessions != nil {
		RegisterSessionsSender(mux, baseURL+"/sessions", h.Sessions)
	}
	if h.Cdrs != nil {
		RegisterCdrsSender(mux, baseURL+"/cdrs", h.Cdrs)
	}
	if h.Tariffs != nil {
		RegisterTariffsSender(mux, baseURL+"/tariffs", h.Tariffs)
	}
	if h.Tokens != nil {
		RegisterTokensReceiver(mux, baseURL+"/tokens", h.Tokens)
	}
	if h.Commands != nil {
		RegisterCommandsReceiver(mux, baseURL+"/commands", h.Commands)
	}
	if h.Chargingprofiles != nil {
		RegisterChargingprofilesReceiver(mux, baseURL+"/chargingprofiles", h.Chargingprofiles)
	}
}

// MSPHandlers groups the functional-module handlers a MSP platform provides.
// A nil field skips registering that module.
type MSPHandlers struct {
	Locations        LocationsReceiverHandler
	Sessions         SessionsReceiverHandler
	Cdrs             CdrsReceiverHandler
	Tariffs          TariffsReceiverHandler
	Tokens           TokensSenderHandler
	Commands         CommandsSenderHandler
	Chargingprofiles ChargingprofilesSenderHandler
}

// RegisterMSP mounts the MSP functional-module endpoints under baseURL;
// each module is mounted at baseURL + "/<module>".
func RegisterMSP(mux *core.Mux, baseURL string, h MSPHandlers) {
	if h.Locations != nil {
		RegisterLocationsReceiver(mux, baseURL+"/locations", h.Locations)
	}
	if h.Sessions != nil {
		RegisterSessionsReceiver(mux, baseURL+"/sessions", h.Sessions)
	}
	if h.Cdrs != nil {
		RegisterCdrsReceiver(mux, baseURL+"/cdrs", h.Cdrs)
	}
	if h.Tariffs != nil {
		RegisterTariffsReceiver(mux, baseURL+"/tariffs", h.Tariffs)
	}
	if h.Tokens != nil {
		RegisterTokensSender(mux, baseURL+"/tokens", h.Tokens)
	}
	if h.Commands != nil {
		RegisterCommandsSender(mux, baseURL+"/commands", h.Commands)
	}
	if h.Chargingprofiles != nil {
		RegisterChargingprofilesSender(mux, baseURL+"/chargingprofiles", h.Chargingprofiles)
	}
}

// HubHandlers groups the functional-module handlers a Hub platform provides.
// A nil field skips registering that module.
type HubHandlers struct {
	Hubclientinfo HubclientinfoSenderHandler
}

// RegisterHub mounts the Hub functional-module endpoints under baseURL;
// each module is mounted at baseURL + "/<module>".
func RegisterHub(mux *core.Mux, baseURL string, h HubHandlers) {
	if h.Hubclientinfo != nil {
		RegisterHubclientinfoSender(mux, baseURL+"/hubclientinfo", h.Hubclientinfo)
	}
}
