// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	_ "embed"
	"sync"

	"github.com/shiv3/gocpi/core/schema"
)

//go:embed schema.json
var schemaJSON []byte

var (
	validatorOnce sync.Once
	validatorInst *schema.Validator
	validatorErr  error
)

// Validator returns the JSON-Schema validator for these OCPI types, built from
// the embedded schema document. It is compiled once and cached.
func Validator() (*schema.Validator, error) {
	validatorOnce.Do(func() {
		validatorInst, validatorErr = schema.New(schemaJSON)
	})
	return validatorInst, validatorErr
}

// ValidateJSON validates raw JSON against the named OCPI type's schema.
func ValidateJSON(typeName string, data []byte) error {
	v, err := Validator()
	if err != nil {
		return err
	}
	return v.Validate(typeName, data)
}
