// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"github.com/shopspring/decimal"
	"time"
)

// Session: The Session object describes one charging session. That doesn't mean it is required that energy
// has been transferred between EV and the Charge Point. It is possible that the EV never took
// energy from the Charge Point because it was instructed not to take energy by the driver.
// But as the EV was connected to the Charge Point, some form of start tariff, park tariff or
// reservation cost might be relevant.
type Session struct {
	CountryCode            string           `json:"country_code" validate:"required,len=2"`
	PartyID                string           `json:"party_id" validate:"required,len=3"`
	ID                     string           `json:"id" validate:"required,max=36"`
	StartDateTime          time.Time        `json:"start_date_time" validate:"required"`
	EndDateTime            *time.Time       `json:"end_date_time,omitempty"`
	Kwh                    decimal.Decimal  `json:"kwh" validate:"required"`
	CDRToken               CdrToken         `json:"cdr_token" validate:"required"`
	AuthMethod             AuthMethod       `json:"auth_method" validate:"required"`
	AuthorizationReference *string          `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	LocationID             string           `json:"location_id" validate:"required,max=36"`
	EVSEUID                string           `json:"evse_uid" validate:"required,max=36"`
	ConnectorID            string           `json:"connector_id" validate:"required,max=36"`
	MeterID                *string          `json:"meter_id,omitempty" validate:"omitempty,max=255"`
	Currency               string           `json:"currency" validate:"required,len=3"`
	ChargingPeriods        []ChargingPeriod `json:"charging_periods,omitempty"`
	TotalCost              *Price           `json:"total_cost,omitempty"`
	Status                 SessionStatus    `json:"status" validate:"required"`
	LastUpdated            time.Time        `json:"last_updated" validate:"required"`
}

// SessionPatch: Partial Session object for PATCH requests. Only fields present will be updated.
// The last_updated field is required.
// When a PATCH request contains the charging_periods field, this SHALL be processed as a request
// to add all the ChargingPeriod objects to the existing Session object. If the request
// charging_periods list is omitted (or contains an empty list), no changes SHALL be made to
// the existing list of charging_periods.
type SessionPatch struct {
	StartDateTime          *time.Time       `json:"start_date_time,omitempty"`
	EndDateTime            *time.Time       `json:"end_date_time,omitempty"`
	Kwh                    *decimal.Decimal `json:"kwh,omitempty"`
	CDRToken               *CdrToken        `json:"cdr_token,omitempty"`
	AuthMethod             *AuthMethod      `json:"auth_method,omitempty"`
	AuthorizationReference *string          `json:"authorization_reference,omitempty" validate:"omitempty,max=36"`
	LocationID             *string          `json:"location_id,omitempty" validate:"omitempty,max=36"`
	EVSEUID                *string          `json:"evse_uid,omitempty" validate:"omitempty,max=36"`
	ConnectorID            *string          `json:"connector_id,omitempty" validate:"omitempty,max=36"`
	MeterID                *string          `json:"meter_id,omitempty" validate:"omitempty,max=255"`
	Currency               *string          `json:"currency,omitempty" validate:"omitempty,len=3"`
	ChargingPeriods        []ChargingPeriod `json:"charging_periods,omitempty"`
	TotalCost              *Price           `json:"total_cost,omitempty"`
	Status                 *SessionStatus   `json:"status,omitempty"`
	LastUpdated            time.Time        `json:"last_updated" validate:"required"`
}

// ChargingPreferences: Contains the charging preferences of an EV driver.
type ChargingPreferences struct {
	ProfileType      ProfileType      `json:"profile_type" validate:"required"`
	DepartureTime    *time.Time       `json:"departure_time,omitempty"`
	EnergyNeed       *decimal.Decimal `json:"energy_need,omitempty"`
	DischargeAllowed *bool            `json:"discharge_allowed,omitempty"`
}

// SessionStatus: Defines the state of a session.
type SessionStatus string

const (
	SessionStatusActive      SessionStatus = "ACTIVE"
	SessionStatusCompleted   SessionStatus = "COMPLETED"
	SessionStatusInvalid     SessionStatus = "INVALID"
	SessionStatusPending     SessionStatus = "PENDING"
	SessionStatusReservation SessionStatus = "RESERVATION"
)

// ProfileType: Different smart charging profile types.
type ProfileType string

const (
	ProfileTypeCheap   ProfileType = "CHEAP"
	ProfileTypeFast    ProfileType = "FAST"
	ProfileTypeGreen   ProfileType = "GREEN"
	ProfileTypeRegular ProfileType = "REGULAR"
)

// ChargingPreferencesResponse: An enum with possible responses to a PUT Charging Preferences request.
type ChargingPreferencesResponse string

const (
	ChargingPreferencesResponseAccepted                ChargingPreferencesResponse = "ACCEPTED"
	ChargingPreferencesResponseDepartureRequired       ChargingPreferencesResponse = "DEPARTURE_REQUIRED"
	ChargingPreferencesResponseEnergyNeedRequired      ChargingPreferencesResponse = "ENERGY_NEED_REQUIRED"
	ChargingPreferencesResponseNotPossible             ChargingPreferencesResponse = "NOT_POSSIBLE"
	ChargingPreferencesResponseProfileTypeNotSupported ChargingPreferencesResponse = "PROFILE_TYPE_NOT_SUPPORTED"
)
