// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// SessionsReceiverClient calls the Sessions receiver interface on a peer.
type SessionsReceiverClient struct {
	c    *core.Client
	base string
}

// NewSessionsReceiverClient binds a client to baseURL (the peer's sessions endpoint URL).
func NewSessionsReceiverClient(c *core.Client, baseURL string) *SessionsReceiverClient {
	return &SessionsReceiverClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *SessionsReceiverClient) GetSession(ctx context.Context, countryCode string, partyID string, sessionID string) (Session, error) {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		var zero Session
		return zero, err
	}
	out, err := core.Decode[Session](resp)
	return out.Data, err
}

func (x *SessionsReceiverClient) PutSession(ctx context.Context, countryCode string, partyID string, sessionID string, body Session) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodPut, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

func (x *SessionsReceiverClient) PatchSession(ctx context.Context, countryCode string, partyID string, sessionID string, body SessionPatch) error {
	u := x.base + "/" + url.PathEscape(countryCode) + "/" + url.PathEscape(partyID) + "/" + url.PathEscape(sessionID)
	resp, err := x.c.Do(ctx, http.MethodPatch, u, body)
	if err != nil {
		return err
	}
	_, err = core.Decode[any](resp)
	return err
}

// SessionsReceiverHandler handles inbound Sessions receiver requests.
type SessionsReceiverHandler interface {
	GetSession(ctx context.Context, countryCode string, partyID string, sessionID string) (Session, *status.Error)
	PutSession(ctx context.Context, countryCode string, partyID string, sessionID string, body Session) *status.Error
	PatchSession(ctx context.Context, countryCode string, partyID string, sessionID string, body SessionPatch) *status.Error
}

// RegisterSessionsReceiver registers h's routes on mux under basePath (the module mount path).
func RegisterSessionsReceiver(mux *core.Mux, basePath string, h SessionsReceiverHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base+"/{country_code}/{party_id}/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		data, herr := h.GetSession(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("session_id"))
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
	mux.Handle(http.MethodPut, base+"/{country_code}/{party_id}/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		var body Session
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PutSession(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("session_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
	mux.Handle(http.MethodPatch, base+"/{country_code}/{party_id}/{session_id}", func(w http.ResponseWriter, r *http.Request) {
		var body SessionPatch
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		if herr := h.PatchSession(r.Context(), r.PathValue("country_code"), r.PathValue("party_id"), r.PathValue("session_id"), body); herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, struct{}{}, status.Success, "")
	})
}
