// Code generated by gocpi codegen. DO NOT EDIT.

package v230

import (
	"context"
	"encoding/json"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/shiv3/gocpi/core"
	"github.com/shiv3/gocpi/core/status"
)

// TokensSenderClient calls the Tokens sender interface on a peer.
type TokensSenderClient struct {
	c    *core.Client
	base string
}

// NewTokensSenderClient binds a client to baseURL (the peer's tokens endpoint URL).
func NewTokensSenderClient(c *core.Client, baseURL string) *TokensSenderClient {
	return &TokensSenderClient{c: c, base: strings.TrimRight(baseURL, "/")}
}

func (x *TokensSenderClient) GetTokens(ctx context.Context, p core.PageOpts) (core.Page[Token], error) {
	u := x.base
	if q := p.Query().Encode(); q != "" {
		u += "?" + q
	}
	resp, err := x.c.Do(ctx, http.MethodGet, u, nil)
	if err != nil {
		return core.Page[Token]{}, err
	}
	out, err := core.Decode[[]Token](resp)
	if err != nil {
		return core.Page[Token]{}, err
	}
	total, limit, next := core.ParsePageHeaders(resp.Header)
	return core.Page[Token]{Items: out.Data, TotalCount: total, Limit: limit, NextURL: next}, nil
}

func (x *TokensSenderClient) PostAuthorize(ctx context.Context, tokenUID string, body LocationReferences) (AuthorizationInfo, error) {
	u := x.base + "/" + url.PathEscape(tokenUID) + "/" + "authorize"
	resp, err := x.c.Do(ctx, http.MethodPost, u, body)
	if err != nil {
		var zero AuthorizationInfo
		return zero, err
	}
	out, err := core.Decode[AuthorizationInfo](resp)
	return out.Data, err
}

// TokensSenderHandler handles inbound Tokens sender requests.
type TokensSenderHandler interface {
	GetTokens(ctx context.Context, req core.PageReq) (core.Page[Token], *status.Error)
	PostAuthorize(ctx context.Context, tokenUID string, body LocationReferences) (AuthorizationInfo, *status.Error)
}

// RegisterTokensSender registers h's routes on mux under basePath (the module mount path).
func RegisterTokensSender(mux *core.Mux, basePath string, h TokensSenderHandler) {
	// basePath may be a full URL or a path; routes use its path.
	bu, _ := url.Parse(basePath)
	base := strings.TrimRight(bu.Path, "/")
	mux.Handle(http.MethodGet, base, func(w http.ResponseWriter, r *http.Request) {
		req, perr := core.ParsePageReq(r.URL.Query())
		if perr != nil {
			_ = core.WriteError(w, status.GenericClient(perr.Error()))
			return
		}
		page, herr := h.GetTokens(r.Context(), req)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		w.Header().Set("X-Total-Count", strconv.Itoa(page.TotalCount))
		if page.Limit > 0 {
			w.Header().Set("X-Limit", strconv.Itoa(page.Limit))
		}
		if page.NextURL != "" {
			w.Header().Set("Link", "<"+page.NextURL+">; rel=\"next\"")
		}
		_ = core.WriteResponse(w, http.StatusOK, page.Items, status.Success, "")
	})
	mux.Handle(http.MethodPost, base+"/{token_uid}/authorize", func(w http.ResponseWriter, r *http.Request) {
		var body LocationReferences
		if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
			_ = core.WriteError(w, status.GenericClient("invalid request body"))
			return
		}
		data, herr := h.PostAuthorize(r.Context(), r.PathValue("token_uid"), body)
		if herr != nil {
			_ = core.WriteError(w, herr)
			return
		}
		_ = core.WriteResponse(w, http.StatusOK, data, status.Success, "")
	})
}
