openapi: 3.1.0
info:
  title: OCPI 2.2.1 - Tariffs Module - Receiver Interface
  description: |
    The Receiver Interface (typically implemented by the eMSP or NSP) allows management of Tariff
    objects. Tariffs are Client Owned Objects, so the endpoints contain the required extra fields:
    country_code, party_id and tariff_id.
  version: 2.2.1
  contact:
    name: EVRoaming Foundation
    url: https://evroaming.org
externalDocs:
  description: OCPI 2.2.1 Specification
  url: https://github.com/ocpi/ocpi/blob/master/mod_tariffs.asciidoc
security:
  - ocpiAuthorization: []
components:
  securitySchemes:
    ocpiAuthorization:
      $ref: "../../components/schema.yaml#/components/securitySchemes/ocpiAuthorization"

paths:
  /tariffs/{country_code}/{party_id}/{tariff_id}:
    get:
      operationId: receiverGetTariff
      summary: Retrieve a Tariff
      tags: [ Tariffs ]
      description: |
        If the CPO wants to check the status of a Tariff in the eMSP's system, it might GET
        the object from the eMSP's system for validation purposes. After all, the CPO is the
        owner of the object, so it would be illogical if the eMSP's system had a different
        status or was missing the object entirely.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TariffIdParameter"
      responses:
        "200":
          description: Successful response containing the requested Tariff.
          headers:
            X-Request-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Request-ID"
            X-Correlation-ID:
              $ref: "../../components/schema.yaml#/components/headers/X-Correlation-ID"
            OCPI-from-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-country-code"
            OCPI-from-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-from-party-id"
            OCPI-to-country-code:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-country-code"
            OCPI-to-party-id:
              $ref: "../../components/schema.yaml#/components/headers/OCPI-to-party-id"
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "../../components/schema.yaml#/components/schemas/OCPIResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "./schema.yaml#/components/schemas/Tariff"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"

    put:
      operationId: receiverPutTariff
      summary: Create or update a Tariff
      tags: [ Tariffs ]
      description: Push new or updated Tariff object to the eMSP.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TariffIdParameter"
      requestBody:
        description: New or updated Tariff object.
        required: true
        content:
          application/json:
            schema:
              $ref: "./schema.yaml#/components/schemas/Tariff"
      responses:
        "200":
          $ref: "../../components/schema.yaml#/components/responses/OCPISuccessResponse"
        "201":
          $ref: "../../components/schema.yaml#/components/responses/OCPICreatedResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"

    delete:
      operationId: receiverDeleteTariff
      summary: Delete a Tariff
      tags: [ Tariffs ]
      description: |
        Delete a Tariff object which is not used any more and will not be used in the future.
        Before deleting a Tariff object, it is RECOMMENDED to ensure that the Tariff object
        is not referenced by any Connector object within the tariff_ids.
      parameters:
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Request-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/X-Correlation-ID"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-from-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-country-code"
        - $ref: "../../components/parameters.yaml#/components/parameters/OCPI-to-party-id"
        - $ref: "../../components/parameters.yaml#/components/parameters/CountryCodeParameter"
        - $ref: "../../components/parameters.yaml#/components/parameters/PartyIdParameter"
        - $ref: "./parameters.yaml#/components/parameters/TariffIdParameter"
      responses:
        "200":
          $ref: "../../components/schema.yaml#/components/responses/OCPISuccessResponse"
        "400":
          $ref: "../../components/schema.yaml#/components/responses/OCPIErrorResponse"
        "401":
          $ref: "../../components/schema.yaml#/components/responses/OCPIUnauthorizedResponse"
        "404":
          $ref: "../../components/schema.yaml#/components/responses/OCPINotFoundResponse"
